### ISSUE TITLE
v16.1.5 fails to run with Node 20.6.0

### ISSUE THREAD

**Issue by p-linnane** [release-it/release-it#1040]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While testing the new Node 20.6.0 release, we found release-it doesn't seem to work with it. Here is the error message:

```shell
/usr/local/Cellar/release-it/16.1.5/bin/release-it -v
  /usr/local/Cellar/release-it/16.1.5/libexec/lib/node_modules/release-it/node_modules/shelljs/src/cat.js:4
  common.register('cat', _cat, {
         ^
  
  TypeError: common.register is not a function
      at Object.<anonymous> (/usr/local/Cellar/release-it/16.1.5/libexec/lib/node_modules/release-it/node_modules/shelljs/src/cat.js:4:8)
      at Module._compile (node:internal/modules/cjs/loader:1241:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
      at Module.load (node:internal/modules/cjs/loader:1091:32)
      at Module._load (node:internal/modules/cjs/loader:938:12)
      at Module.require (node:internal/modules/cjs/loader:1115:19)
      at require (node:internal/modules/helpers:130:18)
      at /usr/local/Cellar/release-it/16.1.5/libexec/lib/node_modules/release-it/node_modules/shelljs/shell.js:25:3
      at Array.forEach (<anonymous>)
      at Object.<anonymous> (/usr/local/Cellar/release-it/16.1.5/libexec/lib/node_modules/release-it/node_modules/shelljs/shell.js:24:23)
  
  Node.js v20.6.0
```
Relates to https://github.com/Homebrew/homebrew-core/pull/141418

**Comment by faradaytrs** [comment]
same here

**Comment by handysuherman** [comment]
same issue aswell in ubuntu 22, node v20.6.0

**Comment by webpro** [comment]
Depends on https://github.com/shelljs/shelljs/issues/1133

**Comment by p-linnane** [comment]
Node v20.6.1 has resolved this issue.

**Comment by webpro** [comment]
The best issues fix themselves :)
