### ISSUE TITLE
Releasing with Gitlab CI_JOB_TOKEN

### ISSUE THREAD

**Issue by Z01d-b3rg** [release-it/release-it#1049]
I'm trying to release on Gitlab using only the `CI_JOB_TOKEN`.  Since the token does not have the permission to push to the repository, I disabled the `git.push` option. I do not want to create a commit, only a new tag.

A new tag can be created using the releases API, but the `release-it`  request doesn't set the `ref` field, which is [required](https://docs.gitlab.com/ee/api/releases/#create-a-release) when creating a release for a non-existing `tag_name`. The error message is:

```
HTTPError: Response code 422 (Unprocessable Entity)
```

Is there any configuration option/ hook I am missing to set this? I could fall back to using a project/ group access token but would prefer not to.

Config:
```
 gitlab: {
    skipChecks: true,
    tokenHeader: 'JOB-TOKEN',
    release: true,
    releaseName: 'Release ${version}',
    releaseNotes: null,
    milestones: [],
    tokenRef: 'CI_JOB_TOKEN',
    certificateAuthorityFile: null,
    assets: null,
    origin: null
  },
  git: {
    push: false,
    requireCleanWorkingDir: false,
    commit: false,
    changelog: 'git log --pretty=format:"* %s (%h)" ${from}...${to}',
    requireBranch: false,
    requireUpstream: true,
    requireCommits: false,
    requireCommitsFail: true,
    commitsPath: '',
    addUntrackedFiles: false,
    commitMessage: 'Release ${version}',
    commitArgs: [],
    tag: true,
    tagExclude: null,
    tagName: null,
    tagMatch: null,
    getLatestTagFromAllRefs: false,
    tagAnnotation: 'Release ${version}',
    tagArgs: [],
    pushArgs: [ '--follow-tags' ],
    pushRepo: ''
  },
  [...]
```

Output:
```
[...]
RELEASE-IT:GITLAB 75: {
  url: 'https://gitlab.com/api/v4/projects/$id/releases',
  json: {
    name: 'Release 2023.10.20',
    tag_name: '2023.10.20.0',
    description: '# [](https://gitlab.com/$project_path/compare/2023.10.18.0...null) (2023-10-20)\n' +
      '\n' +
      '\n' +
      '### Features\n' 
  }
}
RELEASE-IT:GITLAB 75: HTTPError: Response code 422 (Unprocessable Entity)
[...]
```

**Comment by webpro** [comment]
I don't have much experience with GitLab, but I guess the tag must be present in order to create a tag on the remote. Which needs to be pushed first? This is how it works with GitHub: a tag must exist on the remote to create a release.

**Comment by Z01d-b3rg** [comment]
The tag can be created alongside the release if a ref is passed along. It doesn't have to exist beforehand.

From the [documentation](https://docs.gitlab.com/ee/api/releases/#create-a-release):

> If a tag specified in tag_name doesn’t exist, the release is created from ref and tagged with tag_name. It can be a commit SHA, another tag name, or a branch name.

**Comment by dani-CO-CN** [comment]
I was hitting the exact same problem yesterday, if you want to create a release for a non-existing tag via Release API the request needs to contain `id`, `tag_name`, `ref`. (see [gitlab release api docs](https://docs.gitlab.com/ee/api/releases/#create-a-release). This was also reported in https://github.com/release-it/release-it/issues/1115

Maybe this will help someone in the future:
```json
{
  "git": {
    "push": false,
    "tag": true,
    "commit": true,
    "requireCleanWorkingDir": true
  },
  "gitlab": {
    "release": true,
    "tokenRef": "CI_JOB_TOKEN",
    "tokenHeader": "Job-Token",
    "skipChecks": true
  }
}
```

```bash
$ NODE_DEBUG="release-it:*" release-it --ci
[..]
RELEASE-IT:GITLAB 31: HTTPError: Response code 422 (Unprocessable Entity)
    at Request.<anonymous> (file:///home/node/.npm-global/lib/node_modules/release-it/node_modules/got/dist/source/as-promise/index.js:86:42)
    at Object.onceWrapper (node:events:634:26)
    at Request.emit (node:events:531:35)
    at Request._onResponseBase (file:///home/node/.npm-global/lib/node_modules/release-it/node_modules/got/dist/source/core/index.js:726:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Request._onResponse (file:///home/node/.npm-global/lib/node_modules/release-it/node_modules/got/dist/source/core/index.js:768:13) {
  input: undefined,
  code: 'ERR_NON_2XX_3XX_RESPONSE',
    body: '{"name":"Release 0.0.1","tag_name":"0.0.1","description":"some_generated_description"}',
[...]
```

**Comment by thecodegoddess** [comment]
I am experiencing this issue as well

**Comment by webpro** [comment]
Looks like the [referenced issue](https://github.com/release-it/release-it/issues/1115) has a PR attached that should fix this issue. Feel free to help out over there.

**Comment by robross0606** [comment]
FYI, if this is the same issue as #1115, it has been resolved and this should be re-tested.

**Comment by webpro** [comment]
The issue seems to have been addressed, closing this one.
