### ISSUE TITLE
`release-it` inside yarn monorepo with `workspace:*` dependency fails with `EUNSUPPORTEDPROTOCOL: Unsupported URL Type "workspace:": workspace:^`

### ISSUE THREAD

**Issue by mrousavy** [release-it/release-it#1134]
I have a yarn monorepo set up.

Inside my monorepo I have a `packages/` folder with three packages. One of those packages depends on another package in there, so naturally I use the yarn `workspace:*` syntax in it's `package.json`:

```json
{
  ...
  "dependencies": {
    ...
    "my-other-lib": "workspace:*"
  }
}
```

I can publish new versions of this library to npm by using `yarn npm publish` (instead of `npm publish`), but I want to use **release-it** instead.

Unfortunately running `yarn release-it` fails with this error:

```
...
ERROR npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "workspace:": workspace:^

npm error A complete log of this run can be found in: ...-debug-0.log
```

It did properly collect a changelog, but it apparently cannot publish to npm.

Any ideas?

**Comment by mrousavy** [comment]
Logs:

```
0 verbose cli /Users/mrousavy/.nvm/versions/node/v18.18.0/bin/node /Users/mrousavy/.nvm/versions/node/v18.18.0/bin/npm
1 info using npm@10.7.0
2 info using node@v18.18.0
3 silly config:load:file:/Users/mrousavy/.nvm/versions/node/v18.18.0/lib/node_modules/npm/npmrc
4 info found workspace root at /Users/mrousavy/Projects/react-native-nitro
5 silly config:load:file:/Users/mrousavy/Projects/react-native-nitro/.npmrc
6 silly config:load:file:/Users/mrousavy/.npmrc
7 silly config:load:file:/Users/mrousavy/.nvm/versions/node/v18.18.0/etc/npmrc
8 verbose title npm version 0.1.0
9 verbose argv "version" "0.1.0" "--no-git-tag-version"
10 verbose logfile logs-max:10 dir:/Users/mrousavy/.npm/_logs/2024-08-01T22_24_49_914Z-
11 verbose logfile /Users/mrousavy/.npm/_logs/2024-08-01T22_24_49_914Z-debug-0.log
12 silly logfile start cleaning logs, removing 1 files
13 silly logfile done cleaning log files
14 verbose version Not tagging: not in a git repo or no git cmd
15 silly idealTree buildDeps
16 verbose stack Error: Unsupported URL Type "workspace:": workspace:^
16 verbose stack     at unsupportedURLType (/Users/mrousavy/.nvm/versions/node/v18.18.0/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:310:15)
16 verbose stack     at fromURL (/Users/mrousavy/.nvm/versions/node/v18.18.0/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:367:13)
16 verbose stack     at Function.resolve (/Users/mrousavy/.nvm/versions/node/v18.18.0/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:83:12)
16 verbose stack     at #nodeFromEdge (/Users/mrousavy/.nvm/versions/node/v18.18.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1054:22)
16 verbose stack     at #buildDepStep (/Users/mrousavy/.nvm/versions/node/v18.18.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:923:35)
16 verbose stack     at #buildDepStep (/Users/mrousavy/.nvm/versions/node/v18.18.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1041:30)
16 verbose stack     at async Arborist.buildIdealTree (/Users/mrousavy/.nvm/versions/node/v18.18.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:203:7)
16 verbose stack     at async Promise.all (index 1)
16 verbose stack     at async Arborist.reify (/Users/mrousavy/.nvm/versions/node/v18.18.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
16 verbose stack     at async updateWorkspaces (/Users/mrousavy/.nvm/versions/node/v18.18.0/lib/node_modules/npm/lib/utils/update-workspaces.js:36:3)
17 verbose cwd /Users/mrousavy/Projects/react-native-nitro/packages/nitrogen
18 verbose Darwin 23.5.0
19 verbose node v18.18.0
20 verbose npm  v10.7.0
21 error code EUNSUPPORTEDPROTOCOL
22 error Unsupported URL Type "workspace:": workspace:^
23 verbose exit 1
24 verbose code 1
25 silly unfinished npm timer reify 1722551090070
26 silly unfinished npm timer reify:loadTrees 1722551090070
27 silly unfinished npm timer idealTree:buildDeps 1722551092521
28 silly unfinished npm timer idealTree:example 1722551092521
29 error A complete log of this run can be found in: /Users/mrousavy/.npm/_logs/2024-08-01T22_24_49_914Z-debug-0.log
```

**Comment by webpro** [comment]
release-it uses npm under the hood, not yarn.

Not sure if it's an option, but you could give https://github.com/hyoban/release-it-pnpm a shot as pnpm also supports the `workspace:` protocol.

**Comment by setcooki** [comment]
@mrousavy did you ever get this running? i have the same issue using bun. I tried the release-it-pnpm but that forces me to install pnpm workspace. Might as well drop bun and use pnpm instead

**Comment by renanmav** [comment]
bumped into this recently, fixed with:

```json
"release-it": {
  "npm": false
}
```
