### ISSUE TITLE
ERROR getaddrinfo ENOTFOUND bbs.gitlab.com

### ISSUE THREAD

**Issue by DutchmanSA** [release-it/release-it#580]
While using a custom ssh config for gitlab.com, trying to push a release to gitlab fails with the below error:

**ERROR getaddrinfo ENOTFOUND bbs.gitlab.com**

It seems that when trying to push the release, releas-it is not adhering to my ssh config which looks like below:

```
Host bbs.gitlab.com
HostName gitlab.com
IdentityFile ~/.ssh/id_rsa_bbs
PreferredAuthentications publickey
```

The reason I have this setup is due to having 2 differetn accounts on gitlab.com (one for personal and one for my company bbs), so for bbs I use a different aliased host and seperate ssh key. 

Release-it does however work when I make use of the git.pushRepo config and point it to my bbs repo https url, but this is tedious since I dont want to give the username and password everytime. 

**.release-it.json:**
``` json
{
  "git": {
    "tagName": "v${version}"
  },
  "npm": {
    "publish": false
  },
  "gitlab": {
    "release": true,
    "releaseName": "Release ${version}",
    "releaseNotes": null,
    "tokenRef": "GITLAB_BBS_TOKEN",
    "assets": null,
    "origin": null
  }
}
```

**Comment by webpro** [comment]
First I'd like to make sure we distinguish the Git (`push`) part from the GitLab release part.

Is the `git push` part failing, as you describe? You can use this to see better what's going on behind the scenes:

```
DEBUG=release-it:* release-it [...]`
```

**Comment by DutchmanSA** [comment]
The push part actually works 100%. Its only when I need to send a release. I assume this is where it fails while going through the gitlab API?  The changes are pushed to the repo, but no release is created. I then have to do a git pull first to get the latest tags from remote.

![image](https://user-images.githubusercontent.com/3901511/70638805-2ad14b00-1c42-11ea-9e90-0e570ea606d5.png)

**Comment by webpro** [comment]
You can see better what's going on with the command I gave in my previous comment. Maybe there's an issue with custom/private GitLab instances.

It's an annoying situation to find out the GitLab release failed after the push. In this case, you could repeat the release-it process with `--no-increment --no-git` and only do the GitLab release with the same version.

I've just implemented a check in the github plugin to test connection/auth upfront, so users know before pushing anything. Will look into doing the same for the gitlab plugin.

**Comment by webpro** [comment]
> I've just implemented a check in the github plugin to test connection/auth upfront, so users know before pushing anything. Will look into doing the same for the gitlab plugin.

FYI, this is now in the latest `next` release, you can install using `npm install release-it@next`

**Comment by DutchmanSA** [comment]
Here is the debug info in full for attempting a prepatch. Please note that some parts of the project patch and url have been masked out as this is sensitive to share publically.

```
~/Projects/********/********/web-portal(master) » DEBUG=release-it:* release-it prepatch                                                                                                                                              wouternigrini@Wouters-MacBook-Pro-2
  release-it:config {
  release-it:config   cosmiconfig: {
  release-it:config     config: { git: [Object], npm: [Object], gitlab: [Object] },
  release-it:config     filepath: '/Users/wouternigrini/Projects/********/********/web-portal/.release-it.json'
  release-it:config   }
  release-it:config } +0ms
  release-it:config {
  release-it:config   _: [ 'prepatch' ],
  release-it:config   'dry-run': false,
  release-it:config   d: false,
  release-it:config   dryRun: false,
  release-it:config   verbose: 0,
  release-it:config   V: 0,
  release-it:config   increment: 'prepatch',
  release-it:config   ci: undefined,
  release-it:config   git: {
  release-it:config     tagName: 'v${version}',
  release-it:config     changelog: 'git log --pretty=format:"* +4ms (%h)" ${latestTag}...HEAD',
  release-it:config     requireCleanWorkingDir: true,
  release-it:config     requireUpstream: true,
  release-it:config     requireCommits: false,
  release-it:config     addUntrackedFiles: false,
  release-it:config     commit: true,
  release-it:config     commitMessage: 'Release ${version}',
  release-it:config     commitArgs: '',
  release-it:config     tag: true,
  release-it:config     tagAnnotation: 'Release ${version}',
  release-it:config     tagArgs: '',
  release-it:config     push: true,
  release-it:config     pushArgs: '--follow-tags',
  release-it:config     pushRepo: 'origin'
  release-it:config   },
  release-it:config   npm: { publish: false, publishPath: '.', access: null, otp: null },
  release-it:config   gitlab: {
  release-it:config     release: true,
  release-it:config     releaseName: 'Release ${version}',
  release-it:config     releaseNotes: null,
  release-it:config     tokenRef: 'GITLAB_BBS_TOKEN',
  release-it:config     assets: null,
  release-it:config     origin: null
  release-it:config   },
  release-it:config   hooks: {},
  release-it:config   github: {
  release-it:config     release: false,
  release-it:config     releaseName: 'Release ${version}',
  release-it:config     releaseNotes: null,
  release-it:config     preRelease: false,
  release-it:config     draft: false,
  release-it:config     tokenRef: 'GITHUB_TOKEN',
  release-it:config     assets: null,
  release-it:config     host: null,
  release-it:config     timeout: 0,
  release-it:config     proxy: null
  release-it:config   },
  release-it:config   version: {
  release-it:config     increment: 'prepatch',
  release-it:config     isPreRelease: false,
  release-it:config     preReleaseId: undefined
  release-it:config   }
  release-it:config }
  release-it:plugins {
  release-it:plugins   namespace: 'version',
  release-it:plugins   options: {
  release-it:plugins     increment: 'prepatch',
  release-it:plugins     isPreRelease: false,
  release-it:plugins     preReleaseId: undefined
  release-it:plugins   }
  release-it:plugins } +0ms
  release-it:plugins {
  release-it:plugins   namespace: 'gitlab',
  release-it:plugins   options: {
  release-it:plugins     release: true,
  release-it:plugins     releaseName: 'Release ${version}',
  release-it:plugins     releaseNotes: null,
  release-it:plugins     tokenRef: 'GITLAB_BBS_TOKEN',
  release-it:plugins     assets: null,
  release-it:plugins     origin: null,
  release-it:plugins     tagName: 'v${version}',
  release-it:plugins     pushRepo: 'origin',
  release-it:plugins     changelog: 'git log --pretty=format:"* +1ms (%h)" ${latestTag}...HEAD'
  release-it:plugins   }
  release-it:plugins }
  release-it:plugins {
  release-it:plugins   namespace: 'npm',
  release-it:plugins   options: { publish: false, publishPath: '.', access: null, otp: null }
  release-it:plugins } +1ms
  release-it:plugins {
  release-it:plugins   namespace: 'git',
  release-it:plugins   options: {
  release-it:plugins     tagName: 'v${version}',
  release-it:plugins     changelog: 'git log --pretty=format:"* +0ms (%h)" ${latestTag}...HEAD',
  release-it:plugins     requireCleanWorkingDir: true,
  release-it:plugins     requireUpstream: true,
  release-it:plugins     requireCommits: false,
  release-it:plugins     addUntrackedFiles: false,
  release-it:plugins     commit: true,
  release-it:plugins     commitMessage: 'Release ${version}',
  release-it:plugins     commitArgs: '',
  release-it:plugins     tag: true,
  release-it:plugins     tagAnnotation: 'Release ${version}',
  release-it:plugins     tagArgs: '',
  release-it:plugins     push: true,
  release-it:plugins     pushArgs: '--follow-tags',
  release-it:plugins     pushRepo: 'origin'
  release-it:plugins   }
  release-it:plugins }
git@bbs.gitlab.com:bluebeansoftware/web-apps/clients/********/********/common/ui/web-portal.git
  release-it:shell {
  release-it:shell   command: 'git config --get remote.origin.url',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'git@bbs.gitlab.com:bluebeansoftware/web-apps/clients/********/********/common/ui/web-portal.git',
  release-it:shell   stderr: ''
  release-it:shell } +0ms
  release-it:metrics {
  release-it:metrics   statusCode: 200,
  release-it:metrics   statusMessage: 'OK',
  release-it:metrics   url: 'http://www.google-analytics.com/collect'
  release-it:metrics } +0ms
  release-it:shell {
  release-it:shell   command: 'git fetch',
  release-it:shell   options: { cache: true },
  release-it:shell   code: 0,
  release-it:shell   stdout: '',
  release-it:shell   stderr: ''
  release-it:shell } +4s
v0.1.8-0
  release-it:shell {
  release-it:shell   command: 'git describe --tags --abbrev=0',
  release-it:shell   options: { write: false, cache: true },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'v0.1.8-0',
  release-it:shell   stderr: ''
  release-it:shell } +17ms
  release-it:shell {
  release-it:shell   command: 'git log --pretty=format:"* +14ms (%h)" v0.1.8-0...HEAD',
  release-it:shell   options: { write: false, cache: true },
  release-it:shell   code: 0,
  release-it:shell   stdout: '',
  release-it:shell   stderr: ''
  release-it:shell }
  release-it:shell {
  release-it:shell   command: 'git diff-index --quiet HEAD --',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: '',
  release-it:shell   stderr: ''
  release-it:shell } +16ms
git@bbs.gitlab.com:bluebeansoftware/web-apps/clients/********/********/common/ui/web-portal.git
  release-it:shell {
  release-it:shell   command: 'git config --get remote.origin.url',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'git@bbs.gitlab.com:bluebeansoftware/web-apps/clients/********/********/common/ui/web-portal.git',
  release-it:shell   stderr: ''
  release-it:shell } +11ms
refs/heads/master
  release-it:shell {
  release-it:shell   command: 'git symbolic-ref HEAD',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'refs/heads/master',
  release-it:shell   stderr: ''
  release-it:shell } +12ms
origin/master
  release-it:shell {
  release-it:shell   command: 'git for-each-ref --format="%(upstream:short)" refs/heads/master',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'origin/master',
  release-it:shell   stderr: ''
  release-it:shell } +12ms
  release-it:config {
  release-it:config   name: 'web-portal',
  release-it:config   latestVersion: '0.1.8-0',
  release-it:config   version: '0.1.8-1',
  release-it:config   repo: {
  release-it:config     host: 'bbs.gitlab.com',
  release-it:config     owner: 'bluebeansoftware/web-apps/clients/********/********/common/ui',
  release-it:config     project: 'web-portal',
  release-it:config     protocol: 'ssh',
  release-it:config     remote: 'git@bbs.gitlab.com:bluebeansoftware/web-apps/clients/********/********/common/ui/web-portal.git',
  release-it:config     repository: 'bluebeansoftware/web-apps/clients/********/********/common/ui/web-portal'
  release-it:config   },
  release-it:config   changelog: undefined
  release-it:config } +4s

🚀 Let's release web-portal (0.1.8-0...0.1.8-1)


Empty changelog

  release-it:config { version: '0.1.8-1', isPreRelease: true, preReleaseId: null } +2ms
npm ERR! code E404
npm ERR! 404 'web-portal' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! 404 
npm ERR! 404  'web-portal@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
{
  "error": {
    "code": "E404",
    "summary": "'web-portal' is not in the npm registry.\nYou should bug the author to publish it\n(or use the name yourself!)\n\nNote that you can also install from a\ntarball, folder, http url, or git url.",
    "detail": "\n 'web-portal@latest' is not in the npm registry.\nYou should bug the author to publish it (or use the name yourself!)\n\nNote that you can also install from a\ntarball, folder, http url, or git url."
  }
}

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wouternigrini/.npm/_logs/2019-12-14T10_50_14_070Z-debug.log
  release-it:shell {
  release-it:shell   command: 'npm view web-portal dist-tags --json',
  release-it:shell   options: { write: false },
  release-it:shell   code: 1,
  release-it:shell   stdout: '{\n' +
  release-it:shell     '  "error": {\n' +
  release-it:shell     '    "code": "E404",\n' +
  release-it:shell     `    "summary": "'web-portal' is not in the npm registry.\\nYou should bug the author to publish it\\n(or use the name yourself!)\\n\\nNote that you can also install from a\\ntarball, folder, http url, or git url.",\n` +
  release-it:shell     `    "detail": "\\n 'web-portal@latest' is not in the npm registry.\\nYou should bug the author to publish it (or use the name yourself!)\\n\\nNote that you can also install from a\\ntarball, folder, http url, or git url."\n` +
  release-it:shell     '  }\n' +
  release-it:shell     '}',
  release-it:shell   stderr: 'npm ERR! code E404\n' +
  release-it:shell     "npm ERR! 404 'web-portal' is not in the npm registry.\n" +
  release-it:shell     'npm ERR! 404 You should bug the author to publish it\n' +
  release-it:shell     'npm ERR! 404 (or use the name yourself!)\n' +
  release-it:shell     'npm ERR! 404 \n' +
  release-it:shell     'npm ERR! 404 Note that you can also install from a\n' +
  release-it:shell     'npm ERR! 404 tarball, folder, http url, or git url.\n' +
  release-it:shell     'npm ERR! 404 \n' +
  release-it:shell     "npm ERR! 404  'web-portal@latest' is not in the npm registry.\n" +
  release-it:shell     'npm ERR! 404 You should bug the author to publish it (or use the name yourself!)\n' +
  release-it:shell     'npm ERR! 404 \n' +
  release-it:shell     'npm ERR! 404 Note that you can also install from a\n' +
  release-it:shell     'npm ERR! 404 tarball, folder, http url, or git url.\n' +
  release-it:shell     '\n' +
  release-it:shell     'npm ERR! A complete log of this run can be found in:\n' +
  release-it:shell     'npm ERR!     /Users/wouternigrini/.npm/_logs/2019-12-14T10_50_14_070Z-debug.log\n'
  release-it:shell } +514ms

{
  "error": {
    "code": "E404",
    "summary": "'web-portal' is not in the npm registry.\nYou should bug the author to publish it\n(or use the name yourself!)\n\nNote that you can also install from a\ntarball, folder, http url, or git url.",
    "detail": "\n 'web-portal@latest' is not in the npm registry.\nYou should bug the author to publish it (or use the name yourself!)\n\nNote that you can also install from a\ntarball, folder, http url, or git url."
  }
}
WARNING Unable to get pre-release tag(s) from npm registry. Using "next".
v0.1.8-1
  release-it:shell {
  release-it:shell   command: 'npm version 0.1.8-1 --no-git-tag-version',
  release-it:shell   options: {},
  release-it:shell   code: 0,
  release-it:shell   stdout: 'v0.1.8-1',
  release-it:shell   stderr: ''
  release-it:shell } +293ms

Empty release notes

 M package-lock.json
 M package.json
  release-it:shell {
  release-it:shell   command: 'git status --short --untracked-files=no',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'M package-lock.json\n M package.json',
  release-it:shell   stderr: ''
  release-it:shell } +17ms

Changeset:
M package-lock.json
 M package.json

  release-it:shell {
  release-it:shell   command: 'git add . --update',
  release-it:shell   options: {},
  release-it:shell   code: 0,
  release-it:shell   stdout: '',
  release-it:shell   stderr: ''
  release-it:shell } +14ms
? Commit (Release 0.1.8-1)? Yes
[master 1fa2f4c] Release 0.1.8-1
 2 files changed, 2 insertions(+), 2 deletions(-)
  release-it:shell {
  release-it:shell   command: 'git commit --message="Release 0.1.8-1" ',
  release-it:shell   options: {},
  release-it:shell   code: 0,
  release-it:shell   stdout: '[master 1fa2f4c] Release 0.1.8-1\n' +
  release-it:shell     ' 2 files changed, 2 insertions(+), 2 deletions(-)',
  release-it:shell   stderr: ''
  release-it:shell } +16s
? Tag (v0.1.8-1)? Yes
  release-it:shell {
  release-it:shell   command: 'git tag --annotate --message="Release 0.1.8-1"  v0.1.8-1',
  release-it:shell   options: {},
  release-it:shell   code: 0,
  release-it:shell   stdout: '',
  release-it:shell   stderr: ''
  release-it:shell } +4s
? Push? Yes
refs/heads/master
  release-it:shell {
  release-it:shell   command: 'git symbolic-ref HEAD',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'refs/heads/master',
  release-it:shell   stderr: ''
  release-it:shell } +1s
origin/master
  release-it:shell {
  release-it:shell   command: 'git for-each-ref --format="%(upstream:short)" refs/heads/master',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'origin/master',
  release-it:shell   stderr: ''
  release-it:shell } +14ms
To bbs.gitlab.com:bluebeansoftware/web-apps/clients/********/********/common/ui/web-portal.git
   1ce8d38..1fa2f4c  master -> master
 * [new tag]         v0.1.8-1 -> v0.1.8-1
  release-it:shell {
  release-it:shell   command: 'git push --follow-tags origin',
  release-it:shell   options: {},
  release-it:shell   code: 0,
  release-it:shell   stdout: '',
  release-it:shell   stderr: 'To bbs.gitlab.com:bluebeansoftware/web-apps/clients/********/********/common/ui/web-portal.git\n' +
  release-it:shell     '   1ce8d38..1fa2f4c  master -> master\n' +
  release-it:shell     ' * [new tag]         v0.1.8-1 -> v0.1.8-1\n'
  release-it:shell } +5s
? Create a release on GitLab (Release 0.1.8-1)? Yes
  release-it:gitlab {
  release-it:gitlab   url: 'https://bbs.gitlab.com/api/v4/projects/bluebeansoftware%2Fweb-apps%2Fclients%2F********/*******%2F********%2Fcommon%2Fui%2Fweb-portal/releases',
  release-it:gitlab   body: { name: 'Release 0.1.8-1', tag_name: 'v0.1.8-1', description: '-' }
  release-it:gitlab } +0ms
  release-it:gitlab RequestError: getaddrinfo ENOTFOUND bbs.gitlab.com
  release-it:gitlab     at ClientRequest.<anonymous> (/Users/wouternigrini/.npm-global/lib/node_modules/release-it/node_modules/got/source/request-as-event-emitter.js:178:14)
  release-it:gitlab     at Object.onceWrapper (events.js:300:26)
  release-it:gitlab     at ClientRequest.emit (events.js:215:7)
  release-it:gitlab     at ClientRequest.origin.emit (/Users/wouternigrini/.npm-global/lib/node_modules/release-it/node_modules/@szmarczak/http-timer/source/index.js:37:11)
  release-it:gitlab     at TLSSocket.socketErrorListener (_http_client.js:406:9)
  release-it:gitlab     at TLSSocket.emit (events.js:210:5)
  release-it:gitlab     at emitErrorNT (internal/streams/destroy.js:92:8)
  release-it:gitlab     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
  release-it:gitlab     at processTicksAndRejections (internal/process/task_queues.js:80:21) +3s
  release-it:gitlab {
  release-it:gitlab   url: 'https://bbs.gitlab.com/api/v4/projects/bluebeansoftware%2Fweb-apps%2Fclients%2F********%2F********%2Fcommon%2Fui%2Fweb-portal/releases',
  release-it:gitlab   body: { name: 'Release 0.1.8-1', tag_name: 'v0.1.8-1', description: '-' }
  release-it:gitlab } +1s
  release-it:gitlab RequestError: getaddrinfo ENOTFOUND bbs.gitlab.com
  release-it:gitlab     at ClientRequest.<anonymous> (/Users/wouternigrini/.npm-global/lib/node_modules/release-it/node_modules/got/source/request-as-event-emitter.js:178:14)
  release-it:gitlab     at Object.onceWrapper (events.js:300:26)
  release-it:gitlab     at ClientRequest.emit (events.js:215:7)
  release-it:gitlab     at ClientRequest.origin.emit (/Users/wouternigrini/.npm-global/lib/node_modules/release-it/node_modules/@szmarczak/http-timer/source/index.js:37:11)
  release-it:gitlab     at TLSSocket.socketErrorListener (_http_client.js:406:9)
  release-it:gitlab     at TLSSocket.emit (events.js:210:5)
  release-it:gitlab     at emitErrorNT (internal/streams/destroy.js:92:8)
  release-it:gitlab     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
  release-it:gitlab     at processTicksAndRejections (internal/process/task_queues.js:80:21) +3s
  release-it:gitlab {
  release-it:gitlab   url: 'https://bbs.gitlab.com/api/v4/projects/bluebeansoftware%2Fweb-apps%2Fclients%2F********%2F********%2Fcommon%2Fui%2Fweb-portal/releases',
  release-it:gitlab   body: { name: 'Release 0.1.8-1', tag_name: 'v0.1.8-1', description: '-' }
  release-it:gitlab } +2s
  release-it:gitlab RequestError: getaddrinfo ENOTFOUND bbs.gitlab.com
  release-it:gitlab     at ClientRequest.<anonymous> (/Users/wouternigrini/.npm-global/lib/node_modules/release-it/node_modules/got/source/request-as-event-emitter.js:178:14)
  release-it:gitlab     at Object.onceWrapper (events.js:300:26)
  release-it:gitlab     at ClientRequest.emit (events.js:215:7)
  release-it:gitlab     at ClientRequest.origin.emit (/Users/wouternigrini/.npm-global/lib/node_modules/release-it/node_modules/@szmarczak/http-timer/source/index.js:37:11)
  release-it:gitlab     at TLSSocket.socketErrorListener (_http_client.js:406:9)
  release-it:gitlab     at TLSSocket.emit (events.js:210:5)
  release-it:gitlab     at emitErrorNT (internal/streams/destroy.js:92:8)
  release-it:gitlab     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
  release-it:gitlab     at processTicksAndRejections (internal/process/task_queues.js:80:21) +3s
  release-it:metrics { url: 'http://www.google-analytics.com/collect' } +55s
ERROR getaddrinfo ENOTFOUND bbs.gitlab.com
Rolling back changes...
```

**Comment by DutchmanSA** [comment]
> You can see better what's going on with the command I gave in my previous comment. Maybe there's an issue with custom/private GitLab instances.
> 
> It's an annoying situation to find out the GitLab release failed after the push. In this case, you could repeat the release-it process with `--no-increment --no-git` and only do the GitLab release with the same version.
> 
> I've just implemented a check in the github plugin to test connection/auth upfront, so users know before pushing anything. Will look into doing the same for the gitlab plugin.

This still fails with the same error

**Comment by DutchmanSA** [comment]
> npm install release-it@next

Ok so now I get the error stating its not able to auth. Lemme try and recreate the token and test it again.

```
~/Projects/*********/*******/web-portal(master) » release-it -v
v12.5.0-next.2
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~/Projects/*********/*******/web-portal(master) » release-it prepatch
ERROR Could not authenticate with GitLab using environment variable "GITLAB_BBS_TOKEN".
```

**Comment by DutchmanSA** [comment]
> > npm install release-it@next
> 
> Ok so now I get the error stating its not able to auth. Lemme try and recreate the token and test it again.
> 
> ```
> ~/Projects/*********/*******/web-portal(master) » release-it -v
> v12.5.0-next.2
> --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> ~/Projects/*********/*******/web-portal(master) » release-it prepatch
> ERROR Could not authenticate with GitLab using environment variable "GITLAB_BBS_TOKEN".
> ```

Ok still unable to auth. I have created multiple access token, even with all scopes selected. Any suggestions what next to try?

**Comment by DutchmanSA** [comment]
PS, this all works fine if and when I use a normal gotlab url without a custom config. IE when I dont use a url with bbs.gitlab.com.

**Comment by webpro** [comment]
```
ERROR getaddrinfo ENOTFOUND bbs.gitlab.com
```

This error is not a normal 404, but rather a dns issue or something.

This host `https://bbs.gitlab.com` is correct, right? What does this give:

```
curl --header "PRIVATE-TOKEN: $(echo $GITLAB_BBS_TOKEN)" https://bbs.gitlab.com/api/v4/user
```

For your understanding, Git commands (e.g. `git push`) is executed from the command line, whereas the GitLab Release is done using their REST API. This means the former reads your ssh and git configs, but the latter does not.

By the way, I remember testing custom GitLab instances in my `http://localhost:80` (that's why `gitlab.origin` exists), not sure why your situation is different.

**Comment by DutchmanSA** [comment]
> This host `https://bbs.gitlab.com` is correct, right? What does this give:

Well its an alias setup in my ssh config. See my previous posts for reference. This works fine when using git to ssh auth against gitlab.

**Comment by DutchmanSA** [comment]
> curl --header "PRIVATE-TOKEN: $(echo $GITLAB_BBS_TOKEN)" https://bbs.gitlab.com/api/v4/user

this is my result:     curl: (6) Could not resolve host: bbs.gitlab.com

Remember that bbs.gitlab.com is an ssh alias setup. Am I supposed to do something else to get the gitlab api to make use of gitlab.com rather? It seems there is a clash between normal git ssh auth and gitlab auth. Would it not help if there was a release-it config added to specifically target a given gitlab url insteasd of attempting to use the one read from the origin?

**Comment by webpro** [comment]
If the repo origin is `bbs.gitlab.com` (regardless of aliases), then release-it assumes the gitlab api (to do a GitLab Release) to be at `/api/v4` on that domain (not gitlab.com). This is a REST API, it does not use git/ssh. If you want to change the domain for the GitLab API you can set `gitlab.origin: "https://gitlab.com"`.

**Comment by DutchmanSA** [comment]
> If the repo origin is `bbs.gitlab.com` (regardless of aliases), then release-it assumes the gitlab api (to do a GitLab Release) to be at `/api/v4` on that domain (not gitlab.com). This is a REST API, it does not use git/ssh. If you want to change the domain for the GitLab API you can set `gitlab.origin: "https://gitlab.com"`.

Awesome! this works! The reason I never tried that setting was becuase I thought it would use that address as well for the push action. everything works and I am happy for you to close the issue
