### ISSUE TITLE
ReferenceError: tagName is not defined

### ISSUE THREAD

**Issue by agos** [release-it/release-it#619]
Just added `release-it` to a new project and tried a run with the defaults and got the error in the title. Downgraded to `13.0.2` and it's working fine. 

Full error stack:

```
ERROR ReferenceError: tagName is not defined
    at eval (lodash.templateSources[13]:9:10)
    at format (/Users/ago/dev/frontend-pazienti/node_modules/release-it/lib/util.js:25:32)
    at Object.message (/Users/ago/dev/frontend-pazienti/node_modules/release-it/lib/plugin/git/prompts.js:6:50)
    at Prompt.show (/Users/ago/dev/frontend-pazienti/node_modules/release-it/lib/prompt.js:21:23)
    at Git.showPrompt (/Users/ago/dev/frontend-pazienti/node_modules/release-it/lib/plugin/Plugin.js:60:24)
    at Git.step (/Users/ago/dev/frontend-pazienti/node_modules/release-it/lib/plugin/Plugin.js:66:62)
    at Git.release (/Users/ago/dev/frontend-pazienti/node_modules/release-it/lib/plugin/git/Git.js:60:16)
    at runLifeCycleHook (/Users/ago/dev/frontend-pazienti/node_modules/release-it/lib/tasks.js:56:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by webpro** [comment]
Thanks a lot for your bug report, @agos! It has been fixed in [v13.1.1](https://github.com/release-it/release-it/releases/tag/13.1.1).
