### ISSUE TITLE
When using ${name} the release-it fails

### ISSUE THREAD

**Issue by vikaskoppineedi** [release-it/release-it#641]
I have the regular variables in my package.json 

{
  "name": "collections-common-mm",
  "version": "1.0.17",
  "release-it": {
    "hooks": {},
    "git": {
      "changelog": "git log --pretty=format:\"* %s (%h)\" ${latestTag}...HEAD",
      "requireCleanWorkingDir": false,
      "requireUpstream": false,
      "requireCommits": true,
      "addUntrackedFiles": false,
      "commit": true,
      "commitMessage": "Release ${name}-${version}",
      "commitArgs": "",
      "tag": true,
      "tagName": "${version}",
      "tagAnnotation": "${name}-${version}",
      "tagArgs": "",
      "push": true,
      "pushArgs": ["--follow-tags"],
      "pushRepo": ""
      }

Release it fails with the following error 

ERROR ReferenceError: name is not defined
    at eval (lodash.templateSources[12]:9:10)
    at format (/var/lib/jenkins/workspace/s-common-mm-testmigration_master/node_modules/release-it/lib/util.js:26:32)
    at Git.commit (/var/lib/jenkins/workspace/s-common-mm-testmigration_master/node_modules/release-it/lib/plugin/git/Git.js:136:40)
    at task (/var/lib/jenkins/workspace/s-common-mm-testmigration_master/node_modules/release-it/lib/plugin/git/Git.js:60:57)
    at Spinner.show (/var/lib/jenkins/workspace/s-common-mm-testmigration_master/node_modules/release-it/lib/spinner.js:14:23)
    at Git.step (/var/lib/jenkins/workspace/s-common-mm-testmigration_master/node_modules/release-it/lib/plugin/Plugin.js:66:44)
    at Git.release (/var/lib/jenkins/workspace/s-common-mm-testmigration_master/node_modules/release-it/lib/plugin/git/Git.js:60:16)
    at runLifeCycleHook (/var/lib/jenkins/workspace/s-common-mm-testmigration_master/node_modules/release-it/lib/tasks.js:56:25)
    at process._tickCallback (internal/process/next_tick.js:178:7)
ERROR name is not defined

**Comment by webpro** [comment]
That's a bug. Try `npm.name` for now.

**Comment by vikaskoppineedi** [comment]
you are awesome. I am trying to do it as $npm.name or ${npm.name}

**Comment by webpro** [comment]
It's always `${...}` style in release-it config :)

**Comment by vikaskoppineedi** [comment]
Thank you webpro for helping. So i tried to use this " $npm_package_name-$npm_package_version" earlier and this would work too.

**Comment by vikaskoppineedi** [comment]
@webpro I have tried using ${npm.name} and it fails again with 

ERROR ReferenceError: npm is not defined
    at eval (lodash.templateSources[12]:9:10)
    at format (/var/lib/jenkins/workspace/s-common-mm-testmigration_master/node_modules/release-it/lib/util.js:26:32)
    at Git.commit (/var/lib/jenkins/workspace/s-common-mm-testmigration_master/node_modules/release-it/lib/plugin/git/Git.js:136:40)
    at task (/var/lib/jenkins/workspace/s-common-mm-testmigration_master/node_modules/release-it/lib/plugin/git/Git.js:60:57)
    at Spinner.show (/var/lib/jenkins/workspace/s-common-mm-testmigration_master/node_modules/release-it/lib/spinner.js:14:23)
    at Git.step (/var/lib/jenkins/workspace/s-common-mm-testmigration_master/node_modules/release-it/lib/plugin/Plugin.js:66:44)
    at Git.release (/var/lib/jenkins/workspace/s-common-mm-testmigration_master/node_modules/release-it/lib/plugin/git/Git.js:60:16)
    at runLifeCycleHook (/var/lib/jenkins/workspace/s-common-mm-testmigration_master/node_modules/release-it/lib/tasks.js:56:25)
    at process._tickCallback (internal/process/next_tick.js:178:7)
ERROR npm is not defined

**Comment by vikaskoppineedi** [comment]
After the above step fails and it also fails at git push

✖ Git push
ERROR error: The destination you provided is not a full refname (i.e.,
starting with "refs/"). We tried to guess what you meant by:

- Looking for a ref that matches 'HEAD' on the remote side.
- Checking if the <src> being pushed ('HEAD')
  is a ref in "refs/{heads,tags}/". If so we add a corresponding
  refs/{heads,tags}/ prefix on the remote side.

**Comment by webpro** [comment]
I dug into this `${name}` issue and I'll have a fix today. It's not documented to use e.g. `name` outside of hooks, so it's not really a bug, imho, but to prevent any confusion in the future I plan to improve the implementation and documentation regarding this.

**Comment by webpro** [comment]
The available context variables have been extended in [v13.5.3](https://github.com/release-it/release-it/releases/tag/13.5.3)
