### ISSUE TITLE
commitArgs not working

### ISSUE THREAD

**Issue by dhruvdutt** [release-it/release-it#677]
Keeps waiting infinitely:
![image](https://user-images.githubusercontent.com/5961873/85223488-3ff11880-b3e1-11ea-8352-a925d1dd5b28.png)

After removing commit hooks / husky hooks from package.json, it works.

Config:

```
"release-it": {
    "git": {
        "commitArgs": [
        "--no-verify",
        "-n"
        ]
    },
}
```

**Comment by webpro** [comment]
Can you please run the debug command below and reproduce the issue?

```
DEBUG=release-it:* release-it [...]
```

**Comment by rohitchawla22** [comment]
I can confirm that it works that the pushArgs does not work. Any solution for this ?
`
$ DEBUG=release-it:* release-it --no-npm --no-npm.publish --no-git.requireUpstream --git.requireBranch=v1 --ci --no-increment
  release-it:config {
  release-it:config   cosmiconfig: {
  release-it:config     config: {
  release-it:config       'git.requireUpstream': false,
  release-it:config       requireCleanWorkingDir: true,
  release-it:config       git: [Object],
  release-it:config       github: [Object]
  release-it:config     },
  release-it:config     filepath: '/Users/work/Documents/work/apiName/package.json'
  release-it:config   }
  release-it:config } +0ms
  release-it:config {
  release-it:config   system: { 'release-it': '13.6.2', node: 'v12.18.0', os: 'macOS Catalina' }
  release-it:config } +4ms
  release-it:config {
  release-it:config   _: [],
  release-it:config   npm: [
  release-it:config     false,
  release-it:config     { publish: false },
  release-it:config     publish: true,
  release-it:config     publishPath: '.',
  release-it:config     tag: null,
  release-it:config     otp: null,
  release-it:config     ignoreVersion: false,
  release-it:config     skipChecks: false
  release-it:config   ],
  release-it:config   git: {
  release-it:config     requireUpstream: false,
  release-it:config     requireBranch: 'v1',
  release-it:config     requireCleanWorkingDir: false,
  release-it:config     requireCommits: false,
  release-it:config     addUntrackedFiles: false,
  release-it:config     pushArgs: [ '--force', '--no-verify' ],
  release-it:config     changelog: "git log --pretty=format:'* +1ms (%h)' [REV_RANGE]",
  release-it:config     commit: true,
  release-it:config     commitMessage: 'Release ${version}',
  release-it:config     commitArgs: [],
  release-it:config     tag: true,
  release-it:config     tagName: null,
  release-it:config     tagAnnotation: 'Release ${version}',
  release-it:config     tagArgs: [],
  release-it:config     push: true,
  release-it:config     pushRepo: ''
  release-it:config   },
  release-it:config   ci: true,
  release-it:config   increment: false,
  release-it:config   i: false,
  release-it:config   'git.requireUpstream': false,
  release-it:config   requireCleanWorkingDir: true,
  release-it:config   github: {
  release-it:config     release: true,
  release-it:config     releaseName: 'Release ${version}',
  release-it:config     'git.user.email': 'gitExampleEmail',
  release-it:config     'git.user.name': 'work',
  release-it:config     'git.pushArgs': [ '--force', '--no-verify' ],
  release-it:config     releaseNotes: null,
  release-it:config     preRelease: false,
  release-it:config     draft: false,
  release-it:config     tokenRef: 'GITHUB_TOKEN',
  release-it:config     assets: null,
  release-it:config     host: null,
  release-it:config     timeout: 0,
  release-it:config     proxy: null,
  release-it:config     skipChecks: false
  release-it:config   },
  release-it:config   hooks: {},
  release-it:config   gitlab: {
  release-it:config     release: false,
  release-it:config     releaseName: 'Release ${version}',
  release-it:config     releaseNotes: null,
  release-it:config     tokenRef: 'GITLAB_TOKEN',
  release-it:config     assets: null,
  release-it:config     origin: null,
  release-it:config     skipChecks: false
  release-it:config   },
  release-it:config   isUpdate: true,
  release-it:config   version: { increment: false, isPreRelease: false, preReleaseId: undefined }
  release-it:config }
  release-it:plugins {
  release-it:plugins   namespace: 'version',
  release-it:plugins   options: { increment: false, isPreRelease: false, preReleaseId: undefined }
  release-it:plugins } +0ms
  release-it:plugins {
  release-it:plugins   namespace: 'github',
  release-it:plugins   options: {
  release-it:plugins     release: true,
  release-it:plugins     releaseName: 'Release ${version}',
  release-it:plugins     'git.user.email': 'myEmail@domain.com',
  release-it:plugins     'git.user.name': 'work',
  release-it:plugins     'git.pushArgs': [ '--force', '--no-verify' ],
  release-it:plugins     releaseNotes: null,
  release-it:plugins     preRelease: false,
  release-it:plugins     draft: false,
  release-it:plugins     tokenRef: 'GITHUB_TOKEN',
  release-it:plugins     assets: null,
  release-it:plugins     host: null,
  release-it:plugins     timeout: 0,
  release-it:plugins     proxy: null,
  release-it:plugins     skipChecks: false,
  release-it:plugins     tagName: null,
  release-it:plugins     pushRepo: '',
  release-it:plugins     changelog: "git log --pretty=format:'* +2ms (%h)' [REV_RANGE]",
  release-it:plugins     isUpdate: true
  release-it:plugins   }
  release-it:plugins }
  release-it:plugins {
  release-it:plugins   namespace: 'npm',
  release-it:plugins   options: [
  release-it:plugins     false,
  release-it:plugins     { publish: false },
  release-it:plugins     publish: true,
  release-it:plugins     publishPath: '.',
  release-it:plugins     tag: null,
  release-it:plugins     otp: null,
  release-it:plugins     ignoreVersion: false,
  release-it:plugins     skipChecks: false
  release-it:plugins   ]
  release-it:plugins } +0ms
  release-it:plugins {
  release-it:plugins   namespace: 'git',
  release-it:plugins   options: {
  release-it:plugins     requireUpstream: false,
  release-it:plugins     requireBranch: 'v1',
  release-it:plugins     requireCleanWorkingDir: false,
  release-it:plugins     requireCommits: false,
  release-it:plugins     addUntrackedFiles: false,
  release-it:plugins     pushArgs: [ '--force', '--no-verify' ],
  release-it:plugins     changelog: "git log --pretty=format:'* +5ms (%h)' [REV_RANGE]",
  release-it:plugins     commit: true,
  release-it:plugins     commitMessage: 'Release ${version}',
  release-it:plugins     commitArgs: [],
  release-it:plugins     tag: true,
  release-it:plugins     tagName: null,
  release-it:plugins     tagAnnotation: 'Release ${version}',
  release-it:plugins     tagArgs: [],
  release-it:plugins     push: true,
  release-it:plugins     pushRepo: '',
  release-it:plugins     isUpdate: true
  release-it:plugins   }
  release-it:plugins }
v1
  release-it:shell {
  release-it:shell   command: 'git rev-parse --abbrev-ref HEAD',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'v1',
  release-it:shell   stderr: ''
  release-it:shell } +0ms
upstream
  release-it:shell {
  release-it:shell   command: 'git config --get branch.v1.remote',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'upstream',
  release-it:shell   stderr: ''
  release-it:shell } +49ms
  release-it:metrics {
  release-it:metrics   url: 'http://www.google-analytics.com/collect',
  release-it:metrics   statusCode: 200,
  release-it:metrics   statusMessage: 'OK',
  release-it:metrics   payload: 'v=1&tid=UA-108828841-1&cid=6dbd360e-b33a-4369-8c4f-1a350629e1b5&vp=231x29&sd=1-bit&cd1=13.6.2&cd2=v12.18.0&cd3=macOS+Catalina&cd4=1&cd5=0&cd6=0&cd7=0&cd8=null&cd9=undefined&cd11=0&cd12=1&cd13=1&cd14=1&cd15=false&cd16=0&t=event&ec=session&ea=start'
  release-it:metrics } +0ms
https://github.com/Fork/api.git
  release-it:shell {
  release-it:shell   command: 'git remote get-url upstream',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'https://github.com/Fork/api.git',
  release-it:shell   stderr: ''
  release-it:shell } +53ms
  release-it:shell { command: 'git fetch', options: {}, code: 0, stdout: '', stderr: '' } +800ms
1.2.7
  release-it:shell {
  release-it:shell   command: 'git describe --tags --abbrev=0',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: '1.2.7',
  release-it:shell   stderr: ''
  release-it:shell } +81ms
508ccf62aeb78f9b89ce4f10e9664abc4f5ac2b4
  release-it:shell {
  release-it:shell   command: 'git rev-list --tags --skip=1 --max-count=1',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: '508ccf62aeb78f9b89ce4f10e9664abc4f5ac2b4',
  release-it:shell   stderr: ''
  release-it:shell } +64ms
1.3.0
  release-it:shell {
  release-it:shell   command: 'git describe --tags --abbrev=0 508ccf62aeb78f9b89ce4f10e9664abc4f5ac2b4',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: '1.3.0',
  release-it:shell   stderr: ''
  release-it:shell } +80ms
  release-it:config { latestTag: '1.2.7' } +1s
request {
  method: 'GET',
  baseUrl: 'https://github/api/v3',
  headers: {
    accept: 'application/vnd.github.v3+json',
    'user-agent': 'release-it/13.6.2 octokit-rest.js/17.9.0 octokit-core.js/2.5.3 Node.js/12.18.0 (macOS Catalina; x64)'
  },
  mediaType: { format: '', previews: [] },
  request: { timeout: 0, hook: [Function: bound bound register] },
  url: '/user'
}
GET /user - 200 in 241ms
request {
  method: 'GET',
  baseUrl: 'https://github/api/v3',
  headers: {
    accept: 'application/vnd.github.v3+json',
    'user-agent': 'release-it/13.6.2 octokit-rest.js/17.9.0 octokit-core.js/2.5.3 Node.js/12.18.0 (macOS Catalina; x64)'
  },
  mediaType: { format: '', previews: [] },
  request: { timeout: 0, hook: [Function: bound bound register] },
  url: '/repos/{owner}/{repo}/collaborators/{username}',
  owner: 'forkName',
  repo: 'apiName',
  username: 'myFork'
}
GET /repos/forkName/apiName/collaborators/myFork - 204 in 178ms
  release-it:github { owner: 'forkName', repo: 'apiName' } +0ms
request {
  method: 'GET',
  baseUrl: 'https://github/api/v3',
  headers: {
    accept: 'application/vnd.github.v3+json',
    'user-agent': 'release-it/13.6.2 octokit-rest.js/17.9.0 octokit-core.js/2.5.3 Node.js/12.18.0 (macOS Catalina; x64)'
  },
  mediaType: { format: '', previews: [] },
  request: { timeout: 0, hook: [Function: bound bound register] },
  url: '/repos/{owner}/{repo}/releases',
  owner: 'forkName',
  repo: 'apiName',
  per_page: 1,
  page: 1
}
GET /repos/forkName/apiName/releases?per_page=1&page=1 - 200 in 181ms
  release-it:github {
  release-it:github   url: 'https://github/api/v3/repos/forkName/apiName/releases/19624',
  release-it:github   assets_url: 'https://github/api/v3/repos/forkName/apiName/releases/19624/assets',
  release-it:github   upload_url: 'https://github/api/uploads/repos/forkName/apiName/releases/19624/assets{?name,label}',
  release-it:github   html_url: 'https://github/forkName/apiName/releases/tag/1.5.18',
  release-it:github   id: 19624,
  release-it:github   node_id: 'MDc6UmVsZWFzZTE5NjI0',
  release-it:github   tag_name: '1.5.18',
  release-it:github   target_commitish: 'master',
  release-it:github   name: 'Release 1.5.18',
  release-it:github   draft: false,
  release-it:github   author: {
  release-it:github     login: 'myFork',
  release-it:github     id: 1165,
  release-it:github     node_id: 'MDQ6VXNlcjExNjU=',
  release-it:github     avatar_url: 'https://github/avatars/u/1165?',
  release-it:github     gravatar_id: '',
  release-it:github     url: 'https://github/api/v3/users/myFork',
  release-it:github     html_url: 'https://github/myFork',
  release-it:github     followers_url: 'https://github/api/v3/users/myFork/followers',
  release-it:github     following_url: 'https://github/api/v3/users/myFork/following{/other_user}',
  release-it:github     gists_url: 'https://github/api/v3/users/myFork/gists{/gist_id}',
  release-it:github     starred_url: 'https://github/api/v3/users/myFork/starred{/owner}{/repo}',
  release-it:github     subscriptions_url: 'https://github/api/v3/users/myFork/subscriptions',
  release-it:github     organizations_url: 'https://github/api/v3/users/myFork/orgs',
  release-it:github     repos_url: 'https://github/api/v3/users/myFork/repos',
  release-it:github     events_url: 'https://github/api/v3/users/myFork/events{/privacy}',
  release-it:github     received_events_url: 'https://github/api/v3/users/myFork/received_events',
  release-it:github     type: 'User',
  release-it:github     site_admin: false,
  release-it:github     ldap_dn: 'removed for privacy'
  release-it:github   },
  release-it:github   prerelease: false,
  release-it:github   created_at: '2020-07-01T15:33:25Z',
  release-it:github   published_at: '2020-06-05T17:35:41Z',
  release-it:github   assets: [],
  release-it:github   tarball_url: 'https://github/api/v3/repos/forkName/apiName/tarball/1.5.18',
  release-it:github   zipball_url: 'https://github/api/v3/repos/forkName/apiName/zipball/1.5.18',
  release-it:github   body: '* fixed( error log levels): [00000] - Commit message(#2293) (8a0973fe9)\n' +
  release-it:github     '* Merge pull request #1804 from adad/1908283-update-v1 (d71db531c)\n' +
  release-it:github     '* [#1908283] - updating all references of master to v1 since master is now version 2 of the API (af2018179)'
  release-it:github } +182ms
  release-it:config { latestTag: '1.2.7' } +707ms
  release-it:config {
  release-it:config   repo: {
  release-it:config     host: 'github',
  release-it:config     owner: 'forkName',
  release-it:config     project: 'apiName',
  release-it:config     protocol: 'https',
  release-it:config     remote: 'https://github.com/Fork/api.git',
  release-it:config     repository: 'forkName/apiName'
  release-it:config   }
  release-it:config } +6ms
  release-it:shell {
  release-it:shell   command: "git log --pretty=format:'* +4s (%h)' [REV_RANGE]",
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: '',
  release-it:shell   stderr: ''
  release-it:shell }
  release-it:config {
  release-it:config   name: 'rocket-mortgage-api',
  release-it:config   latestVersion: '1.3.1',
  release-it:config   version: '1.3.1',
  release-it:config   changelog: undefined
  release-it:config } +3s
🚀 Let's update rocket-mortgage-api (currently at 1.3.1)
Empty changelog
  release-it:config { version: '1.3.1', isPreRelease: false, preReleaseId: null } +1ms
npm ERR! Version not changed, might want --allow-same-version

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/work/.npm/_logs/2020-07-02T03_03_42_199Z-debug.log
  release-it:shell {
  release-it:shell   command: 'npm version 1.3.1 --no-git-tag-version',
  release-it:shell   options: {},
  release-it:shell   code: 1,
  release-it:shell   stdout: '',
  release-it:shell   stderr: 'npm ERR! Version not changed, might want --allow-same-version\n' +
  release-it:shell     '\n' +
  release-it:shell     'npm ERR! A complete log of this run can be found in:\n' +
  release-it:shell     'npm ERR!     /Users/work/.npm/_logs/2020-07-02T03_03_42_199Z-debug.log\n'
  release-it:shell } +2s
WARNING Did not update version in package.json, etc. (already at 1.3.1).
  release-it:config { tagName: '1.3.1' } +2s
  release-it:config { tagName: '1.3.1' } +0ms
  release-it:shell {
  release-it:shell   command: 'git status --short --untracked-files=no',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: '',
  release-it:shell   stderr: ''
  release-it:shell } +60ms
Empty changeset
  release-it:shell {
  release-it:shell   command: [ 'git', 'add', '.', '--update' ],
  release-it:shell   options: {},
  release-it:shell   stdout: '',
  release-it:shell   stderr: ''
  release-it:shell } +52ms

On branch v1
Your branch and 'upstream/v1' have diverged,
and have 1 and 30 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean
  release-it:shell {
  release-it:shell   error: Error: Command failed with exit code 1: git commit --message Release 1.3.1
  release-it:shell   On branch v1
  release-it:shell   Your branch and 'upstream/v1' have diverged,
  release-it:shell   and have 1 and 30 different commits each, respectively.
  release-it:shell     (use "git pull" to merge the remote branch into yours)
  release-it:shell   
  release-it:shell   nothing to commit, working tree clean
  release-it:shell       at makeError (/Users/work/Documents/work/apiName/node_modules/release-it/node_modules/execa/lib/error.js:59:11)
  release-it:shell       at handlePromise (/Users/work/Documents/work/apiName/node_modules/release-it/node_modules/execa/index.js:114:26)
  release-it:shell       at processTicksAndRejections (internal/process/task_queues.js:97:5)
  release-it:shell       at async Shell.execWithArguments (/Users/work/Documents/work/apiName/node_modules/release-it/lib/shell.js:77:39)
  release-it:shell       at async Git.release (/Users/work/Documents/work/apiName/node_modules/release-it/lib/plugin/git/Git.js:65:5)
  release-it:shell       at async runLifeCycleHook (/Users/work/Documents/work/apiName/node_modules/release-it/lib/tasks.js:54:28)
  release-it:shell       at async runTasks (/Users/work/Documents/work/apiName/node_modules/release-it/lib/tasks.js:99:9) {
  release-it:shell     shortMessage: 'Command failed with exit code 1: git commit --message Release 1.3.1',
  release-it:shell     command: 'git commit --message Release 1.3.1',
  release-it:shell     exitCode: 1,
  release-it:shell     signal: undefined,
  release-it:shell     signalDescription: undefined,
  release-it:shell     stdout: 'On branch v1\n' +
  release-it:shell       "Your branch and 'upstream/v1' have diverged,\n" +
  release-it:shell       'and have 1 and 30 different commits each, respectively.\n' +
  release-it:shell       '  (use "git pull" to merge the remote branch into yours)\n' +
  release-it:shell       '\n' +
  release-it:shell       'nothing to commit, working tree clean',
  release-it:shell     stderr: '',
  release-it:shell     failed: true,
  release-it:shell     timedOut: false,
  release-it:shell     isCanceled: false,
  release-it:shell     killed: false
  release-it:shell   }
  release-it:shell } +260ms
  release-it:git Error: Command failed with exit code 1: git commit --message Release 1.3.1
  release-it:git On branch v1
  release-it:git Your branch and 'upstream/v1' have diverged,
  release-it:git and have 1 and 30 different commits each, respectively.
  release-it:git   (use "git pull" to merge the remote branch into yours)
  release-it:git 
  release-it:git nothing to commit, working tree clean
  release-it:git     at Shell.execWithArguments (/Users/work/Documents/work/apiName/node_modules/release-it/lib/shell.js:87:29)
  release-it:git     at processTicksAndRejections (internal/process/task_queues.js:97:5) +0ms
WARNING No changes to commit. The latest commit will be tagged.
  release-it:shell {
  release-it:shell   command: [ 'git', 'tag', '--annotate', '--message', 'Release 1.3.1', '1.3.1' ],
  release-it:shell   options: {},
  release-it:shell   stdout: '',
  release-it:shell   stderr: ''
  release-it:shell } +69ms
refs/heads/v1
  release-it:shell {
  release-it:shell   command: 'git symbolic-ref HEAD',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'refs/heads/v1',
  release-it:shell   stderr: ''
  release-it:shell } +70ms
upstream/v1
  release-it:shell {
  release-it:shell   command: 'git for-each-ref --format="%(upstream:short)" refs/heads/v1',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'upstream/v1',
  release-it:shell   stderr: ''
  release-it:shell } +62ms
  release-it:shell {
  release-it:shell   error: Error: Command failed with exit code 1: git push --force --no-verify
  release-it:shell   remote: Searching for secrets...        
  release-it:shell   remote: Lines scanned: 3486        
  release-it:shell   remote: Finished looking for secrets.        
  release-it:shell   remote: Visit http://shorty/secretOverride/ for override documentation.        
  release-it:shell   remote: error: GH006: Protected branch update failed for refs/heads/v1.        
  release-it:shell   remote: error: Cannot force-push to this protected branch        
  release-it:shell   To https://github.com/Fork/api.git
  release-it:shell    ! [remote rejected]     v1 -> v1 (protected branch hook declined)
  release-it:shell   error: failed to push some refs to 'https://github.com/Fork/api.git'
  release-it:shell       at makeError (/Users/work/Documents/work/apiName/node_modules/release-it/node_modules/execa/lib/error.js:59:11)
  release-it:shell       at handlePromise (/Users/work/Documents/work/apiName/node_modules/release-it/node_modules/execa/index.js:114:26)
  release-it:shell       at processTicksAndRejections (internal/process/task_queues.js:97:5)
  release-it:shell       at async Shell.execWithArguments (/Users/work/Documents/work/apiName/node_modules/release-it/lib/shell.js:77:39)
  release-it:shell       at async Git.release (/Users/work/Documents/work/apiName/node_modules/release-it/lib/plugin/git/Git.js:67:15)
  release-it:shell       at async runLifeCycleHook (/Users/work/Documents/work/apiName/node_modules/release-it/lib/tasks.js:54:28)
  release-it:shell       at async runTasks (/Users/work/Documents/work/apiName/node_modules/release-it/lib/tasks.js:99:9) {
  release-it:shell     shortMessage: 'Command failed with exit code 1: git push --force --no-verify',
  release-it:shell     command: 'git push --force --no-verify',
  release-it:shell     exitCode: 1,
  release-it:shell     signal: undefined,
  release-it:shell     signalDescription: undefined,
  release-it:shell     stdout: '',
  release-it:shell     stderr: 'remote: Searching for secrets...        \n' +
  release-it:shell       'remote: Lines scanned: 3486        \n' +
  release-it:shell       'remote: Finished looking for secrets.        \n' +
  release-it:shell       'remote: Visit http://shorty/secretOverride/ for override documentation.        \n' +
  release-it:shell       'remote: error: GH006: Protected branch update failed for refs/heads/v1.        \n' +
  release-it:shell       'remote: error: Cannot force-push to this protected branch        \n' +
  release-it:shell       'To https://github.com/Fork/api.git\n' +
  release-it:shell       ' ! [remote rejected]     v1 -> v1 (protected branch hook declined)\n' +
  release-it:shell       "error: failed to push some refs to 'https://github.com/Fork/api.git'",
  release-it:shell     failed: true,
  release-it:shell     timedOut: false,
  release-it:shell     isCanceled: false,
  release-it:shell     killed: false
  release-it:shell   }
  release-it:shell } +4s
  release-it:metrics {
  release-it:metrics   url: 'http://www.google-analytics.com/collect',
  release-it:metrics   statusCode: 200,
  release-it:metrics   statusMessage: 'OK',
  release-it:metrics   payload: 't=exception&exd=Error%3A+remote%3A+Searching+for+secrets...++++++++'
  release-it:metrics } +12s
ERROR remote: Searching for secrets...        
remote: Lines scanned: 3486        
remote: Finished looking for secrets.        
remote: Visit http://shorty/secretOverride/ for override documentation.        
remote: error: GH006: Protected branch update failed for refs/heads/v1.        
remote: error: Cannot force-push to this protected branch        
To https://github.com/Fork/api.git
 ! [remote rejected]     v1 -> v1 (protected branch hook declined)
error: failed to push some refs to 'https://github.com/Fork/api.git'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

My release-it configs looks like this 
`
"release-it": {
    "git.requireUpstream": false,
    "requireCleanWorkingDir": true,
    "git": {
      "requireCleanWorkingDir": false,
      "requireUpstream": false,
      "requireCommits": false,
      "addUntrackedFiles": false,
      "pushArgs": ["--force", "--no-verify"],
      "changelog": "git log --pretty=format:'* %s (%h)' [REV_RANGE]"
    },
    "github": {
      "release": true,
      "releaseName": "Release ${version}",
      "git.user.email": "userEmail",
      "git.user.name": "userName",
      "git.pushArgs": ["--force", "--no-verify"]
    }
  }
`

**Comment by webpro** [comment]
@rohitchawla22 Please check your logs. The output is this:

```
release-it:shell error: Error: Command failed with exit code 1: git push --force --no-verify
release-it:shell remote: Searching for secrets...
release-it:shell remote: Lines scanned: 3486
release-it:shell remote: Finished looking for secrets.
release-it:shell remote: Visit http://shorty/secretOverride/ for override documentation.
release-it:shell remote: error: GH006: Protected branch update failed for refs/heads/v1.
release-it:shell remote: error: Cannot force-push to this protected branch
release-it:shell To https://github.com/Fork/api.git
release-it:shell ! [remote rejected] v1 -> v1 (protected branch hook declined)
release-it:shell error: failed to push some refs to 'https://github.com/Fork/api.git'
```

So the `pushArgs` are actually being used and you have a different issue.

**Comment by webpro** [comment]
Closing due to inactivity
