### ISSUE TITLE
Release with LANG=de_DE.UTF-8 but works with LANG=en_US

### ISSUE THREAD

**Issue by tristanlins** [release-it/release-it#728]
I tried a release on a new project, but it fails with an error.

`DEBUG=release-it:* yarn release` failed

<details>

```
$ DEBUG=release-it:* yarn release
yarn run v1.22.10
$ release-it
  release-it:config {
  release-it:config   cosmiconfig: {
  release-it:config     config: { npm: false },
  release-it:config     filepath: '/../package.json'
  release-it:config   }
  release-it:config } +0ms
  release-it:config {
  release-it:config   system: { 'release-it': '14.2.2', node: 'v14.15.3', os: 'Linux 5.9' }
  release-it:config } +5ms
  release-it:config {
  release-it:config   _: [],
  release-it:config   increment: undefined,
  release-it:config   ci: false,
  release-it:config   npm: false,
  release-it:config   hooks: {},
  release-it:config   git: {
  release-it:config     changelog: 'git log --pretty=format:"* +1ms (%h)" ${from}...${to}',
  release-it:config     requireCleanWorkingDir: true,
  release-it:config     requireBranch: false,
  release-it:config     requireUpstream: true,
  release-it:config     requireCommits: false,
  release-it:config     addUntrackedFiles: false,
  release-it:config     commit: true,
  release-it:config     commitMessage: 'Release ${version}',
  release-it:config     commitArgs: [],
  release-it:config     tag: true,
  release-it:config     tagName: null,
  release-it:config     tagAnnotation: 'Release ${version}',
  release-it:config     tagArgs: [],
  release-it:config     push: true,
  release-it:config     pushArgs: [ '--follow-tags' ],
  release-it:config     pushRepo: ''
  release-it:config   },
  release-it:config   github: {
  release-it:config     release: false,
  release-it:config     releaseName: 'Release ${version}',
  release-it:config     releaseNotes: null,
  release-it:config     preRelease: false,
  release-it:config     draft: false,
  release-it:config     tokenRef: 'GITHUB_TOKEN',
  release-it:config     assets: null,
  release-it:config     host: null,
  release-it:config     timeout: 0,
  release-it:config     proxy: null,
  release-it:config     skipChecks: false
  release-it:config   },
  release-it:config   gitlab: {
  release-it:config     release: false,
  release-it:config     releaseName: 'Release ${version}',
  release-it:config     releaseNotes: null,
  release-it:config     tokenRef: 'GITLAB_TOKEN',
  release-it:config     assets: null,
  release-it:config     origin: null,
  release-it:config     skipChecks: false
  release-it:config   },
  release-it:config   isUpdate: false,
  release-it:config   version: {
  release-it:config     increment: undefined,
  release-it:config     isPreRelease: false,
  release-it:config     preReleaseId: undefined
  release-it:config   }
  release-it:config }
  release-it:plugins {
  release-it:plugins   namespace: 'version',
  release-it:plugins   options: {
  release-it:plugins     increment: undefined,
  release-it:plugins     isPreRelease: false,
  release-it:plugins     preReleaseId: undefined
  release-it:plugins   }
  release-it:plugins } +0ms
  release-it:plugins {
  release-it:plugins   namespace: 'git',
  release-it:plugins   options: {
  release-it:plugins     changelog: 'git log --pretty=format:"* +7ms (%h)" ${from}...${to}',
  release-it:plugins     requireCleanWorkingDir: true,
  release-it:plugins     requireBranch: false,
  release-it:plugins     requireUpstream: true,
  release-it:plugins     requireCommits: false,
  release-it:plugins     addUntrackedFiles: false,
  release-it:plugins     commit: true,
  release-it:plugins     commitMessage: 'Release ${version}',
  release-it:plugins     commitArgs: [],
  release-it:plugins     tag: true,
  release-it:plugins     tagName: null,
  release-it:plugins     tagAnnotation: 'Release ${version}',
  release-it:plugins     tagArgs: [],
  release-it:plugins     push: true,
  release-it:plugins     pushArgs: [ '--follow-tags' ],
  release-it:plugins     pushRepo: '',
  release-it:plugins     isUpdate: false
  release-it:plugins   }
  release-it:plugins }
  release-it:shell {
  release-it:shell   command: 'git diff --quiet HEAD',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: '',
  release-it:shell   stderr: ''
  release-it:shell } +0ms
master
  release-it:shell {
  release-it:shell   command: 'git rev-parse --abbrev-ref HEAD',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'master',
  release-it:shell   stderr: ''
  release-it:shell } +13ms
  release-it:metrics {
  release-it:metrics   url: 'http://www.google-analytics.com/collect',
  release-it:metrics   statusCode: 200,
  release-it:metrics   statusMessage: 'OK',
  release-it:metrics   payload: 'v=1&tid=UA-108828841-1&cid=95e02fb4-f02c-493e-a8a2-9b26489f5b17&cd1=14.2.2&cd2=v14.15.3&cd3=Linux+5.9&cd4=1&cd5=0&cd6=0&cd7=0&cd8=null&cd9=undefined&cd11=0&cd12=1&cd13=0&cd14=0&cd15=undefined&cd16=0&t=event&ec=session&ea=start'
  release-it:metrics } +0ms
origin
  release-it:shell {
  release-it:shell   command: 'git config --get branch.master.remote',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'origin',
  release-it:shell   stderr: ''
  release-it:shell } +11ms
gitlab:node/repo.git
  release-it:shell {
  release-it:shell   command: 'git remote get-url origin',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'gitlab:node/repo.git',
  release-it:shell   stderr: ''
  release-it:shell } +10ms
  release-it:shell { command: 'git fetch', options: {}, code: 0, stdout: '', stderr: '' } +413ms
fatal: Keine Namen gefunden, kann nichts beschreiben.
  release-it:shell {
  release-it:shell   command: 'git describe --tags --abbrev=0',
  release-it:shell   options: { write: false },
  release-it:shell   code: 128,
  release-it:shell   stdout: '',
  release-it:shell   stderr: 'fatal: Keine Namen gefunden, kann nichts beschreiben.\n'
  release-it:shell } +9ms
  release-it:config { latestTag: null } +499ms
refs/heads/master
  release-it:shell {
  release-it:shell   command: 'git symbolic-ref HEAD',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'refs/heads/master',
  release-it:shell   stderr: ''
  release-it:shell } +7ms
origin/master
  release-it:shell {
  release-it:shell   command: 'git for-each-ref --format="%(upstream:short)" refs/heads/master',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'origin/master',
  release-it:shell   stderr: ''
  release-it:shell } +7ms
  release-it:config {
  release-it:config   repo: {
  release-it:config     host: 'gitlab',
  release-it:config     owner: 'node',
  release-it:config     project: 'project',
  release-it:config     protocol: 'ssh',
  release-it:config     remote: 'gitlab:node/repo.git',
  release-it:config     repository: 'repo'
  release-it:config   }
  release-it:config } +13ms
* Downgrade version in package.json (105ac28)
* fixup! fixup! Disable npm publishing (41fd062)
* fixup! Disable npm publishing (3138375)
* Disable npm publishing (0506734)
* Add examples to README (17de775)
* Recent development and added tests (ca96472)
* [CI] Fixup image name (fb0bce3)
* add initial gitlab ci config (bc05e65)
* Add release-it to build (0129ff8)
* Initial commit (3a6ed84)  release-it:shell {
  release-it:shell   command: 'git log --pretty=format:"* +10ms (%h)"',
  release-it:shell   options: {},
  release-it:shell   code: 0,
  release-it:shell   stdout: '* Downgrade version in package.json (105ac28)\n' +
  release-it:shell     '* fixup! fixup! Disable npm publishing (41fd062)\n' +
  release-it:shell     '* fixup! Disable npm publishing (3138375)\n' +
  release-it:shell     '* Disable npm publishing (0506734)\n' +
  release-it:shell     '* Add examples to README (17de775)\n' +
  release-it:shell     '* Recent development and added tests (ca96472)\n' +
  release-it:shell     '* [CI] Fixup image name (fb0bce3)\n' +
  release-it:shell     '* add initial gitlab ci config (bc05e65)\n' +
  release-it:shell     '* Add release-it to build (0129ff8)\n' +
  release-it:shell     '* Initial commit (3a6ed84)',
  release-it:shell   stderr: ''
  release-it:shell }
  release-it:config {
  release-it:config   name: 'project',
  release-it:config   latestVersion: '0.0.0',
  release-it:config   version: undefined,
  release-it:config   changelog: '* Downgrade version in package.json (105ac28)\n' +
  release-it:config     '* fixup! fixup! Disable npm publishing (41fd062)\n' +
  release-it:config     '* fixup! Disable npm publishing (3138375)\n' +
  release-it:config     '* Disable npm publishing (0506734)\n' +
  release-it:config     '* Add examples to README (17de775)\n' +
  release-it:config     '* Recent development and added tests (ca96472)\n' +
  release-it:config     '* [CI] Fixup image name (fb0bce3)\n' +
  release-it:config     '* add initial gitlab ci config (bc05e65)\n' +
  release-it:config     '* Add release-it to build (0129ff8)\n' +
  release-it:config     '* Initial commit (3a6ed84)'
  release-it:config } +11ms

🚀 Let's release project (currently at 0.0.0)


Changelog:
* Downgrade version in package.json (105ac28)
* fixup! fixup! Disable npm publishing (41fd062)
* fixup! Disable npm publishing (3138375)
* Disable npm publishing (0506734)
* Add examples to README (17de775)
* Recent development and added tests (ca96472)
* [CI] Fixup image name (fb0bce3)
* add initial gitlab ci config (bc05e65)
* Add release-it to build (0129ff8)
* Initial commit (3a6ed84)

? Select increment (next version): major (1.0.0)
  release-it:config { version: '1.0.0', isPreRelease: false, preReleaseId: null } +2s
  release-it:config { tagName: '1.0.0' } +1ms
  release-it:shell {
  release-it:shell   command: 'git status --short --untracked-files=no',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: '',
  release-it:shell   stderr: ''
  release-it:shell } +2s

Empty changeset

  release-it:shell {
  release-it:shell   command: [ 'git', 'add', '.', '--update' ],
  release-it:shell   options: {},
  release-it:shell   stdout: '',
  release-it:shell   stderr: ''
  release-it:shell } +12ms
? Commit (Release 1.0.0)? Yes

Auf Branch master
Ihr Branch ist auf demselben Stand wie 'origin/master'.

nichts zu committen, Arbeitsverzeichnis unverändert
  release-it:shell {
  release-it:shell   error: Error: Command failed with exit code 1: git commit --message Release 1.0.0
  release-it:shell   Auf Branch master
  release-it:shell   Ihr Branch ist auf demselben Stand wie 'origin/master'.
  release-it:shell
  release-it:shell   nichts zu committen, Arbeitsverzeichnis unverändert
  release-it:shell       at makeError (/../node_modules/execa/lib/error.js:59:11)
  release-it:shell       at handlePromise (/../node_modules/execa/index.js:114:26)
  release-it:shell       at processTicksAndRejections (internal/process/task_queues.js:93:5)
  release-it:shell       at async Shell.execWithArguments (/../node_modules/release-it/lib/shell.js:79:39)
  release-it:shell       at async Prompt.show (/../node_modules/release-it/lib/prompt.js:29:32)
  release-it:shell       at async Git.release (/../node_modules/release-it/lib/plugin/git/Git.js:80:5)
  release-it:shell       at async runLifeCycleHook (/../node_modules/release-it/lib/tasks.js:50:28)
  release-it:shell       at async runTasks (/../node_modules/release-it/lib/tasks.js:102:9) {
  release-it:shell     shortMessage: 'Command failed with exit code 1: git commit --message Release 1.0.0',
  release-it:shell     command: 'git commit --message Release 1.0.0',
  release-it:shell     exitCode: 1,
  release-it:shell     signal: undefined,
  release-it:shell     signalDescription: undefined,
  release-it:shell     stdout: 'Auf Branch master\n' +
  release-it:shell       "Ihr Branch ist auf demselben Stand wie 'origin/master'.\n" +
  release-it:shell       '\n' +
  release-it:shell       'nichts zu committen, Arbeitsverzeichnis unverändert',
  release-it:shell     stderr: '',
  release-it:shell     failed: true,
  release-it:shell     timedOut: false,
  release-it:shell     isCanceled: false,
  release-it:shell     killed: false
  release-it:shell   }
  release-it:shell } +2s
  release-it:git Error: Command failed with exit code 1: git commit --message Release 1.0.0
  release-it:git Auf Branch master
  release-it:git Ihr Branch ist auf demselben Stand wie 'origin/master'.
  release-it:git
  release-it:git nichts zu committen, Arbeitsverzeichnis unverändert
  release-it:git     at Shell.execWithArguments (/../node_modules/release-it/lib/shell.js:89:29)
  release-it:git     at processTicksAndRejections (internal/process/task_queues.js:93:5)
  release-it:git     at async Prompt.show (/../node_modules/release-it/lib/prompt.js:29:32)
  release-it:git     at async Git.release (/../node_modules/release-it/lib/plugin/git/Git.js:80:5)
  release-it:git     at async runLifeCycleHook (/../node_modules/release-it/lib/tasks.js:50:28)
  release-it:git     at async runTasks (/../node_modules/release-it/lib/tasks.js:102:9) +0ms
  release-it:metrics {
  release-it:metrics   url: 'http://www.google-analytics.com/collect',
  release-it:metrics   statusCode: 200,
  release-it:metrics   statusMessage: 'OK',
  release-it:metrics   payload: 't=exception&exd=Error%3A+Error%3A+Command+failed+with+exit+code+1%3A+git+commit+--message+Release+1.0.0'
  release-it:metrics } +5s
ERROR Error: Command failed with exit code 1: git commit --message Release 1.0.0
Auf Branch master
Ihr Branch ist auf demselben Stand wie 'origin/master'.

nichts zu committen, Arbeitsverzeichnis unverändert
Rolling back changes...
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

</details>

But when I change my terminal language to `en_US` the release works fine, `LANG=en_US DEBUG=release-it:* yarn release`

<details>

```
$ LANG=en_US DEBUG=release-it:* yarn release
yarn run v1.22.10
$ release-it
  release-it:config {
  release-it:config   cosmiconfig: {
  release-it:config     config: { npm: false },
  release-it:config     filepath: '/../package.json'
  release-it:config   }
  release-it:config } +0ms
  release-it:config {
  release-it:config   system: { 'release-it': '14.2.2', node: 'v14.15.3', os: 'Linux 5.9' }
  release-it:config } +4ms
  release-it:config {
  release-it:config   _: [],
  release-it:config   increment: undefined,
  release-it:config   ci: false,
  release-it:config   npm: false,
  release-it:config   hooks: {},
  release-it:config   git: {
  release-it:config     changelog: 'git log --pretty=format:"* +1ms (%h)" ${from}...${to}',
  release-it:config     requireCleanWorkingDir: true,
  release-it:config     requireBranch: false,
  release-it:config     requireUpstream: true,
  release-it:config     requireCommits: false,
  release-it:config     addUntrackedFiles: false,
  release-it:config     commit: true,
  release-it:config     commitMessage: 'Release ${version}',
  release-it:config     commitArgs: [],
  release-it:config     tag: true,
  release-it:config     tagName: null,
  release-it:config     tagAnnotation: 'Release ${version}',
  release-it:config     tagArgs: [],
  release-it:config     push: true,
  release-it:config     pushArgs: [ '--follow-tags' ],
  release-it:config     pushRepo: ''
  release-it:config   },
  release-it:config   github: {
  release-it:config     release: false,
  release-it:config     releaseName: 'Release ${version}',
  release-it:config     releaseNotes: null,
  release-it:config     preRelease: false,
  release-it:config     draft: false,
  release-it:config     tokenRef: 'GITHUB_TOKEN',
  release-it:config     assets: null,
  release-it:config     host: null,
  release-it:config     timeout: 0,
  release-it:config     proxy: null,
  release-it:config     skipChecks: false
  release-it:config   },
  release-it:config   gitlab: {
  release-it:config     release: false,
  release-it:config     releaseName: 'Release ${version}',
  release-it:config     releaseNotes: null,
  release-it:config     tokenRef: 'GITLAB_TOKEN',
  release-it:config     assets: null,
  release-it:config     origin: null,
  release-it:config     skipChecks: false
  release-it:config   },
  release-it:config   isUpdate: false,
  release-it:config   version: {
  release-it:config     increment: undefined,
  release-it:config     isPreRelease: false,
  release-it:config     preReleaseId: undefined
  release-it:config   }
  release-it:config }
  release-it:plugins {
  release-it:plugins   namespace: 'version',
  release-it:plugins   options: {
  release-it:plugins     increment: undefined,
  release-it:plugins     isPreRelease: false,
  release-it:plugins     preReleaseId: undefined
  release-it:plugins   }
  release-it:plugins } +0ms
  release-it:plugins {
  release-it:plugins   namespace: 'git',
  release-it:plugins   options: {
  release-it:plugins     changelog: 'git log --pretty=format:"* +5ms (%h)" ${from}...${to}',
  release-it:plugins     requireCleanWorkingDir: true,
  release-it:plugins     requireBranch: false,
  release-it:plugins     requireUpstream: true,
  release-it:plugins     requireCommits: false,
  release-it:plugins     addUntrackedFiles: false,
  release-it:plugins     commit: true,
  release-it:plugins     commitMessage: 'Release ${version}',
  release-it:plugins     commitArgs: [],
  release-it:plugins     tag: true,
  release-it:plugins     tagName: null,
  release-it:plugins     tagAnnotation: 'Release ${version}',
  release-it:plugins     tagArgs: [],
  release-it:plugins     push: true,
  release-it:plugins     pushArgs: [ '--follow-tags' ],
  release-it:plugins     pushRepo: '',
  release-it:plugins     isUpdate: false
  release-it:plugins   }
  release-it:plugins }
  release-it:shell {
  release-it:shell   command: 'git diff --quiet HEAD',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: '',
  release-it:shell   stderr: ''
  release-it:shell } +0ms
master
  release-it:shell {
  release-it:shell   command: 'git rev-parse --abbrev-ref HEAD',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'master',
  release-it:shell   stderr: ''
  release-it:shell } +9ms
origin
  release-it:shell {
  release-it:shell   command: 'git config --get branch.master.remote',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'origin',
  release-it:shell   stderr: ''
  release-it:shell } +7ms
  release-it:metrics {
  release-it:metrics   url: 'http://www.google-analytics.com/collect',
  release-it:metrics   statusCode: 200,
  release-it:metrics   statusMessage: 'OK',
  release-it:metrics   payload: 'v=1&tid=UA-108828841-1&cid=8fb9c6b9-7975-4c8a-91bf-f39dd6d442ca&cd1=14.2.2&cd2=v14.15.3&cd3=Linux+5.9&cd4=1&cd5=0&cd6=0&cd7=0&cd8=null&cd9=undefined&cd11=0&cd12=1&cd13=0&cd14=0&cd15=undefined&cd16=0&t=event&ec=session&ea=start'
  release-it:metrics } +0ms
gitlab:node/project.git
  release-it:shell {
  release-it:shell   command: 'git remote get-url origin',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'gitlab:node/project.git',
  release-it:shell   stderr: ''
  release-it:shell } +12ms
  release-it:shell { command: 'git fetch', options: {}, code: 0, stdout: '', stderr: '' } +558ms
fatal: No names found, cannot describe anything.
  release-it:shell {
  release-it:shell   command: 'git describe --tags --abbrev=0',
  release-it:shell   options: { write: false },
  release-it:shell   code: 128,
  release-it:shell   stdout: '',
  release-it:shell   stderr: 'fatal: No names found, cannot describe anything.\n'
  release-it:shell } +9ms
  release-it:config { latestTag: null } +624ms
refs/heads/master
  release-it:shell {
  release-it:shell   command: 'git symbolic-ref HEAD',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'refs/heads/master',
  release-it:shell   stderr: ''
  release-it:shell } +8ms
origin/master
  release-it:shell {
  release-it:shell   command: 'git for-each-ref --format="%(upstream:short)" refs/heads/master',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'origin/master',
  release-it:shell   stderr: ''
  release-it:shell } +7ms
  release-it:config {
  release-it:config   repo: {
  release-it:config     host: 'gitlab',
  release-it:config     owner: 'node',
  release-it:config     project: 'project',
  release-it:config     protocol: 'ssh',
  release-it:config     remote: 'gitlab:node/project.git',
  release-it:config     repository: 'node/project'
  release-it:config   }
  release-it:config } +15ms
* Downgrade version in package.json (105ac28)
* fixup! fixup! Disable npm publishing (41fd062)
* fixup! Disable npm publishing (3138375)
* Disable npm publishing (0506734)
* Add examples to README (17de775)
* Recent development and added tests (ca96472)
* [CI] Fixup image name (fb0bce3)
* add initial gitlab ci config (bc05e65)
* Add release-it to build (0129ff8)
* Initial commit (3a6ed84)  release-it:shell {
  release-it:shell   command: 'git log --pretty=format:"* +9ms (%h)"',
  release-it:shell   options: {},
  release-it:shell   code: 0,
  release-it:shell   stdout: '* Downgrade version in package.json (105ac28)\n' +
  release-it:shell     '* fixup! fixup! Disable npm publishing (41fd062)\n' +
  release-it:shell     '* fixup! Disable npm publishing (3138375)\n' +
  release-it:shell     '* Disable npm publishing (0506734)\n' +
  release-it:shell     '* Add examples to README (17de775)\n' +
  release-it:shell     '* Recent development and added tests (ca96472)\n' +
  release-it:shell     '* [CI] Fixup image name (fb0bce3)\n' +
  release-it:shell     '* add initial gitlab ci config (bc05e65)\n' +
  release-it:shell     '* Add release-it to build (0129ff8)\n' +
  release-it:shell     '* Initial commit (3a6ed84)',
  release-it:shell   stderr: ''
  release-it:shell }
  release-it:config {
  release-it:config   name: 'project',
  release-it:config   latestVersion: '0.0.0',
  release-it:config   version: undefined,
  release-it:config   changelog: '* Downgrade version in package.json (105ac28)\n' +
  release-it:config     '* fixup! fixup! Disable npm publishing (41fd062)\n' +
  release-it:config     '* fixup! Disable npm publishing (3138375)\n' +
  release-it:config     '* Disable npm publishing (0506734)\n' +
  release-it:config     '* Add examples to README (17de775)\n' +
  release-it:config     '* Recent development and added tests (ca96472)\n' +
  release-it:config     '* [CI] Fixup image name (fb0bce3)\n' +
  release-it:config     '* add initial gitlab ci config (bc05e65)\n' +
  release-it:config     '* Add release-it to build (0129ff8)\n' +
  release-it:config     '* Initial commit (3a6ed84)'
  release-it:config } +10ms

🚀 Let's release project (currently at 0.0.0)


Changelog:
* Downgrade version in package.json (105ac28)
* fixup! fixup! Disable npm publishing (41fd062)
* fixup! Disable npm publishing (3138375)
* Disable npm publishing (0506734)
* Add examples to README (17de775)
* Recent development and added tests (ca96472)
* [CI] Fixup image name (fb0bce3)
* add initial gitlab ci config (bc05e65)
* Add release-it to build (0129ff8)
* Initial commit (3a6ed84)

? Select increment (next version): major (1.0.0)
  release-it:config { version: '1.0.0', isPreRelease: false, preReleaseId: null } +2s
  release-it:config { tagName: '1.0.0' } +0ms
  release-it:shell {
  release-it:shell   command: 'git status --short --untracked-files=no',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: '',
  release-it:shell   stderr: ''
  release-it:shell } +2s

Empty changeset

  release-it:shell {
  release-it:shell   command: [ 'git', 'add', '.', '--update' ],
  release-it:shell   options: {},
  release-it:shell   stdout: '',
  release-it:shell   stderr: ''
  release-it:shell } +10ms
? Commit (Release 1.0.0)? Yes

On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
  release-it:shell {
  release-it:shell   error: Error: Command failed with exit code 1: git commit --message Release 1.0.0
  release-it:shell   On branch master
  release-it:shell   Your branch is up to date with 'origin/master'.
  release-it:shell
  release-it:shell   nothing to commit, working tree clean
  release-it:shell       at makeError (/../node_modules/execa/lib/error.js:59:11)
  release-it:shell       at handlePromise (/../node_modules/execa/index.js:114:26)
  release-it:shell       at processTicksAndRejections (internal/process/task_queues.js:93:5)
  release-it:shell       at async Shell.execWithArguments (/../node_modules/release-it/lib/shell.js:79:39)
  release-it:shell       at async Prompt.show (/../node_modules/release-it/lib/prompt.js:29:32)
  release-it:shell       at async Git.release (/../node_modules/release-it/lib/plugin/git/Git.js:80:5)
  release-it:shell       at async runLifeCycleHook (/../node_modules/release-it/lib/tasks.js:50:28)
  release-it:shell       at async runTasks (/../node_modules/release-it/lib/tasks.js:102:9) {
  release-it:shell     shortMessage: 'Command failed with exit code 1: git commit --message Release 1.0.0',
  release-it:shell     command: 'git commit --message Release 1.0.0',
  release-it:shell     exitCode: 1,
  release-it:shell     signal: undefined,
  release-it:shell     signalDescription: undefined,
  release-it:shell     stdout: 'On branch master\n' +
  release-it:shell       "Your branch is up to date with 'origin/master'.\n" +
  release-it:shell       '\n' +
  release-it:shell       'nothing to commit, working tree clean',
  release-it:shell     stderr: '',
  release-it:shell     failed: true,
  release-it:shell     timedOut: false,
  release-it:shell     isCanceled: false,
  release-it:shell     killed: false
  release-it:shell   }
  release-it:shell } +1s
  release-it:git Error: Command failed with exit code 1: git commit --message Release 1.0.0
  release-it:git On branch master
  release-it:git Your branch is up to date with 'origin/master'.
  release-it:git
  release-it:git nothing to commit, working tree clean
  release-it:git     at Shell.execWithArguments (/../node_modules/release-it/lib/shell.js:89:29)
  release-it:git     at processTicksAndRejections (internal/process/task_queues.js:93:5)
  release-it:git     at async Prompt.show (/../node_modules/release-it/lib/prompt.js:29:32)
  release-it:git     at async Git.release (/../node_modules/release-it/lib/plugin/git/Git.js:80:5)
  release-it:git     at async runLifeCycleHook (/../node_modules/release-it/lib/tasks.js:50:28)
  release-it:git     at async runTasks (/../node_modules/release-it/lib/tasks.js:102:9) +0ms
WARNING No changes to commit. The latest commit will be tagged.
? Tag (1.0.0)? Yes
  release-it:shell {
  release-it:shell   command: [ 'git', 'tag', '--annotate', '--message', 'Release 1.0.0', '1.0.0' ],
  release-it:shell   options: {},
  release-it:shell   stdout: '',
  release-it:shell   stderr: ''
  release-it:shell } +12s
? Push? Yes
  release-it:shell {
  release-it:shell   command: [ 'git', 'push', '--follow-tags' ],
  release-it:shell   options: {},
  release-it:shell   stdout: '',
  release-it:shell   stderr: 'To gitlab:node/project.git\n' +
  release-it:shell     ' * [new tag]         1.0.0 -> 1.0.0'
  release-it:shell } +6s
  release-it:metrics {
  release-it:metrics   url: 'http://www.google-analytics.com/collect',
  release-it:metrics   statusCode: 200,
  release-it:metrics   statusMessage: 'OK',
  release-it:metrics   payload: 't=event&ec=session&ea=end'
  release-it:metrics } +22s
🏁 Done (in 22s.)
Done in 22.60s.
```

</details>

May be related to #716

**Comment by tristanlins** [comment]
The issue seems to only occur on the first release.
Each following release works fine :thinking:

**Comment by webpro** [comment]
Thanks, @tristanlins! There is indeed a (mis)match on the output of a `git commit`, to distinguish whether the commit actually failed or when the commit was empty (which is not a problem, release-it just shows a warning). This output is expected to contain some English text (the regex is `/nothing (added )?to commit/`) so this will result in an error when using a different language.

I think it's a bit of an edge case, usually there is a change (e.g. in `package.json`). It doesn't scale well, but for now I've added a fix for the German language anyway.
