### ISSUE TITLE
release-it - publishing current package json version instead of next release version.

### ISSUE THREAD

**Issue by KumarSumitD** [release-it/release-it#732]
Hi,
I had a existing monorepo(lerna). with only one package. That package is published to artifactory as docker image, not npm module.
Recently i created a new package which i want to publish in artifactory as npm module using release-it. But it is trying to publish current version instead of future release version.

Project structure - 
Project - 
-----packages
               ---------- Package 1 - published as docker image to artifactory
               ---------- Package 2 - want to publish as npm module to artifactory using release-it
release-it is installed in root package.json.
Below are my files which are related to this. I have removed things which were unnecessary to make it readable. 
**Root package.json  - release-it is installed in root**
```
{
  "name": "*****",
  "version": "*****",
  "description": "*****",
  "main": "index.js",
  "private": true,
  "scripts": {
  },
  "repository": {
    "type": "git",
    "url": "*****"
  },
  "author": "*****",
  "license": "ISC",
  "bugs": {
    "url": "*****"
  },
  "homepage": "*****",
  "devDependencies": {
    "release-it": "^14.2.2",
  }
}

```

**New Package which needs to be published as npm module - package.json -  no release-it here**
```
{
  "name": "****",
  "version": "0.0.1",
  "description": "****",
  "repository": {
    "type": "git",
    "url": "****",
    "directory": "packages/package-2"
  },
  "files": [
    "dist/",
    "loader/"
  ],
  "scripts": {
  },
  "dependencies": {
  },
  "license": "MIT"
}
```

**Release it config -**
```
const { PACKAGE_NAME } = process.env;
const format = `${PACKAGE_NAME}-\${version}`;
const lastTag = `git describe --match "${PACKAGE_NAME}-v*" --abbrev=0`;
module.exports = {
  git: {
    commitMessage: '${version}',
    requireUpstream: false,
    tagName: 'v${version}',
  },
  github: {
    release: true,
    releaseName: '${version}',
    releaseNotes: null,
    tokenRef: '*****', // Needed for credentials pipeline function in Jenkins/CI,
   requireCleanWorkingDir: false, // ci leaves strayed files sometimes
  addUntrackedFiles: true, // track updated files for doc site
  commitMessage: format,
  tagName: `${PACKAGE_NAME}-v\${version}`,
  tagAnnotation: '', // release-it has a bug where this will be duplicated, so we must force it to empty string
  changelog: `git log --pretty=format:"* %s (%h)" $(${lastTag})...\${to} -- ${PACKAGE_NAME}`,
releaseName: format
  },
  npm: {
    // need skipChecks due to a timeout issue when pinging to artifactory
    // see https://github.com/release-it/release-it/issues/637
    skipChecks: true,
    publishPath: "dist"
  },
};
```

**Jenkins Job Log - sharing only from the time when release-it kicked in.**

```
+ DEBUG='release-it:*' PACKAGE_NAME=package-2 ../../node_modules/.bin/release patch '--preRelease='
13:27:17  2021-01-27T18:27:17.810Z release-it:config {
13:27:17    cosmiconfig: {
13:27:17      config: { git: [Object], github: [Object], npm: [Object] },
13:27:17      filepath: '/home/jenkins/workspace/****_master/.release-it.js'
13:27:17    }
13:27:17  }
13:27:17  2021-01-27T18:27:17.812Z release-it:config {
13:27:17    system: { 'release-it': '14.2.2', node: 'v12.18.3', os: 'Linux 4.4' }
13:27:17  }
13:27:17  2021-01-27T18:27:17.813Z release-it:config {
13:27:17    ci: true,
13:27:17    increment: 'patch',
13:27:17    dryRun: false,
13:27:17    git: {
13:27:17      commitMessage: 'package-2-${version}',
13:27:17      requireUpstream: false,
13:27:17      tagName: 'package-2-v${version}',
13:27:17      requireCleanWorkingDir: false,
13:27:17      addUntrackedFiles: true,
13:27:17      tagAnnotation: '',
13:27:17      changelog: 'git log --pretty=format:"* %s (%h)" $(git describe --match "package-2-v*" --abbrev=0)...${to} -- package-2',
13:27:17      requireBranch: false,
13:27:17      requireCommits: false,
13:27:17      commit: true,
13:27:17      commitArgs: [],
13:27:17      tag: true,
13:27:17      tagArgs: [],
13:27:17      push: true,
13:27:17      pushArgs: [ '--follow-tags' ],
13:27:17      pushRepo: ''
13:27:17    },
13:27:17    github: {
13:27:17      release: true,
13:27:17      releaseName: 'package-2-${version}',
13:27:17      releaseNotes: null,
13:27:17      tokenRef: '*****', // Same as what we have in release it config
13:27:17      preRelease: false,
13:27:17      draft: false,
13:27:17      assets: null,
13:27:17      host: null,
13:27:17      timeout: 0,
13:27:17      proxy: null,
13:27:17      skipChecks: false
13:27:17    },
13:27:17    npm: {
13:27:17      skipChecks: true,
13:27:17      publishPath: 'dist',
13:27:17      publish: true,
13:27:17      tag: null,
13:27:17      otp: null,
13:27:17      ignoreVersion: false,
13:27:17      timeout: 10
13:27:17    },
13:27:17    hooks: {},
13:27:17    gitlab: {
13:27:17      release: false,
13:27:17      releaseName: 'Release ${version}',
13:27:17      releaseNotes: null,
13:27:17      tokenRef: '*****',
13:27:17      assets: null,
13:27:17      origin: null,
13:27:17      skipChecks: false
13:27:17    },
13:27:17    isUpdate: false,
13:27:17    version: { increment: 'patch', isPreRelease: false, preReleaseId: undefined }
13:27:17  }
13:27:17  2021-01-27T18:27:17.822Z release-it:plugins {
13:27:17    namespace: 'npm',
13:27:17    options: {
13:27:17      skipChecks: true,
13:27:17      publishPath: 'dist',
13:27:17      publish: true,
13:27:17      tag: null,
13:27:17      otp: null,
13:27:17      ignoreVersion: false,
13:27:17      timeout: 10
13:27:17    }
13:27:17  }
13:27:17  2021-01-27T18:27:17.823Z release-it:plugins {
13:27:17    namespace: 'github',
13:27:17    options: {
13:27:17      release: true,
13:27:17      releaseName: 'package-2-${version}',
13:27:17      releaseNotes: null,
13:27:17      tokenRef: 'GITHUB_TOKEN_PSW',
13:27:17      preRelease: false,
13:27:17      draft: false,
13:27:17      assets: null,
13:27:17      host: null,
13:27:17      timeout: 0,
13:27:17      proxy: null,
13:27:17      skipChecks: false,
13:27:17      tagName: 'package-2-v${version}',
13:27:17      pushRepo: '',
13:27:17      changelog: 'git log --pretty=format:"* %s (%h)" $(git describe --match "package-2-v*" --abbrev=0)...${to} -- package-2',
13:27:17      isUpdate: false
13:27:17    }
13:27:17  }
13:27:17  2021-01-27T18:27:17.823Z release-it:plugins {
13:27:17    namespace: 'version',
13:27:17    options: { increment: 'patch', isPreRelease: false, preReleaseId: undefined }
13:27:17  }
13:27:17  2021-01-27T18:27:17.827Z release-it:plugins {
13:27:17    namespace: 'git',
13:27:17    options: {
13:27:17      commitMessage: 'package-2-${version}',
13:27:17      requireUpstream: false,
13:27:17      tagName: 'package-2-v${version}',
13:27:17      requireCleanWorkingDir: false,
13:27:17      addUntrackedFiles: true,
13:27:17      tagAnnotation: '',
13:27:17      changelog: 'git log --pretty=format:"* %s (%h)" $(git describe --match "package-2-v*" --abbrev=0)...${to} -- package-2',
13:27:17      requireBranch: false,
13:27:17      requireCommits: false,
13:27:17      commit: true,
13:27:17      commitArgs: [],
13:27:17      tag: true,
13:27:17      tagArgs: [],
13:27:17      push: true,
13:27:17      pushArgs: [ '--follow-tags' ],
13:27:17      pushRepo: '',
13:27:17      isUpdate: false
13:27:17    }
13:27:17  }
13:27:17  HEAD
13:27:17  2021-01-27T18:27:17.835Z release-it:shell {
13:27:17    command: 'git rev-parse --abbrev-ref HEAD',
13:27:17    options: { write: false },
13:27:17    code: 0,
13:27:17    stdout: 'HEAD',
13:27:17    stderr: ''
13:27:17  }
13:27:17  2021-01-27T18:27:17.839Z release-it:shell {
13:27:17    command: 'git config --get branch.HEAD.remote',
13:27:17    options: { write: false },
13:27:17    code: 1,
13:27:17    stdout: '',
13:27:17    stderr: ''
13:27:17  }
13:27:17  https://github.com/*****/*****.git
13:27:17  2021-01-27T18:27:17.844Z release-it:shell {
13:27:17    command: 'git remote get-url origin',
13:27:17    options: { write: false },
13:27:17    code: 0,
13:27:17    stdout: 'https://github.com/*****/*****.git',
13:27:17    stderr: ''
13:27:17  }
13:27:17  2021-01-27T18:27:17.851Z release-it:metrics {
13:27:17    url: 'http://www.google-analytics.com/collect',
13:27:17    statusCode: 200,
13:27:17    statusMessage: 'OK',
13:27:17    payload: 'v=1&tid=UA-108828841-1&cid=08f52e21-9883-4bab-8cb3-db4e0e73381b&cd1=14.2.2&cd2=v12.18.3&cd3=Linux+4.4&cd4=1&cd5=0&cd6=0&cd7=0&cd8=null&cd9=undefined&cd11=1&cd12=1&cd13=1&cd14=1&cd15=patch&cd16=0&t=event&ec=session&ea=start'
13:27:17  }
13:27:18  2021-01-27T18:27:17.995Z release-it:shell { command: 'git fetch', options: {}, code: 0, stdout: '', stderr: '' }
13:27:18  v1.0.13
13:27:18  2021-01-27T18:27:18.002Z release-it:shell {
13:27:18    command: 'git describe --tags --abbrev=0',
13:27:18    options: { write: false },
13:27:18    code: 0,
13:27:18    stdout: 'v1.0.13',
13:27:18    stderr: ''
13:27:18  }
13:27:18  2021-01-27T18:27:18.002Z release-it:config { latestTag: 'v1.0.13' }
13:27:18  2021-01-27T18:27:18.003Z release-it:config {
13:27:18    repo: {
13:27:18      host: 'github.com',
13:27:18      owner: '*****',
13:27:18      project: '*****',
13:27:18      protocol: 'https',
13:27:18      remote: 'https://github.com/*****/*****.git',
13:27:18      repository: '*****/*****'
13:27:18    }
13:27:18  }
13:27:18  2021-01-27T18:27:18.004Z release-it:config { latestTag: 'v1.0.13' }
13:27:18  request {
13:27:18    method: 'GET',
13:27:18    baseUrl: 'https://api.github.com',
13:27:18    headers: {
13:27:18      accept: 'application/vnd.github.v3+json',
13:27:18      'user-agent': 'release-it/14.2.2 octokit-rest.js/18.0.9 octokit-core.js/3.2.5 Node.js/12.18.3 (linux; x64)'
13:27:18    },
13:27:18    mediaType: { format: '', previews: [] },
13:27:18    request: { timeout: 0, hook: [Function: bound bound register] },
13:27:18    url: '/user'
13:27:18  }
13:27:18  GET /user - 200 in 85ms
13:27:18  request {
13:27:18    method: 'GET',
13:27:18    baseUrl: 'https://api.github.com',
13:27:18    headers: {
13:27:18      accept: 'application/vnd.github.v3+json',
13:27:18      'user-agent': 'release-it/14.2.2 octokit-rest.js/18.0.9 octokit-core.js/3.2.5 Node.js/12.18.3 (linux; x64)'
13:27:18    },
13:27:18    mediaType: { format: '', previews: [] },
13:27:18    request: { timeout: 0, hook: [Function: bound bound register] },
13:27:18    url: '/repos/{owner}/{repo}/collaborators/{username}',
13:27:18    owner: '*****',
13:27:18    repo: '*****',
13:27:18    username: ****
13:27:18  }
13:27:18  GET /repos/*****/*****/collaborators/**** - 204 in 86ms
13:27:18  fatal: No names found, cannot describe anything.
13:27:18  2021-01-27T18:27:18.188Z release-it:shell {
13:27:18    command: 'git log --pretty=format:"* %s (%h)" $(git describe --match "package-2-v*" --abbrev=0)...HEAD -- package-2',
13:27:18    options: { write: false },
13:27:18    code: 0,
13:27:18    stdout: '',
13:27:18    stderr: 'fatal: No names found, cannot describe anything.\n'
13:27:18  }
13:27:18  2021-01-27T18:27:18.189Z release-it:config {
13:27:18    name: '@*****/package-2',
13:27:18    latestVersion: '0.0.1',
13:27:18    version: '0.0.2',
13:27:18    changelog: undefined
13:27:18  }
13:27:18  🚀 Let's release @*****/package-2 (0.0.1...0.0.2)
13:27:18  Empty changelog
13:27:18  2021-01-27T18:27:18.189Z release-it:config { version: '0.0.2', isPreRelease: false, preReleaseId: null }
13:27:18  v0.0.2
13:27:18  2021-01-27T18:27:18.387Z release-it:shell {
13:27:18    command: 'npm version 0.0.2 --no-git-tag-version',
13:27:18    options: {},
13:27:18    code: 0,
13:27:18    stdout: 'v0.0.2',
13:27:18    stderr: ''
13:27:18  }
13:27:18  2021-01-27T18:27:18.388Z release-it:config { tagName: 'package-2-v0.0.2' }
13:27:18  2021-01-27T18:27:18.388Z release-it:config { tagName: 'package-2-v0.0.2' }
13:27:18   M package-lock.json
13:27:18   M package.json
13:27:18   M src/components/*****/readme.md
13:27:18  2021-01-27T18:27:18.395Z release-it:shell {
13:27:18    command: 'git status --short --untracked-files=no',
13:27:18    options: { write: false },
13:27:18    code: 0,
13:27:18    stdout: 'M package-lock.json\n' +
13:27:18      ' M package.json\n' +
13:27:18      ' M src/components/*****/readme.md',
13:27:18    stderr: ''
13:27:18  }
13:27:18  Changeset:
13:27:18  M package-lock.json
13:27:18   M package.json
13:27:18   M src/components/*****/readme.md
13:27:18  2021-01-27T18:27:18.541Z release-it:shell {
13:27:18    command: [ 'git', 'add', '.', '--all' ],
13:27:18    options: {},
13:27:18    stdout: '',
13:27:18    stderr: ''
13:27:18  }
13:27:19  npm notice 
13:27:19  npm notice package: @*****/package-2@0.0.1
13:27:19  npm notice === Tarball Contents === 
13:27:19  npm notice 1.1kB package.json
13:27:19  npm notice 4.0kB readme.md   
13:27:19  npm notice === Tarball Details === 
13:27:19  npm notice name:          @*****/package-2         
13:27:19  npm notice version:       0.0.1                                   
13:27:19  npm notice package size:  2.5 kB                                  
13:27:19  npm notice unpacked size: 5.0 kB                                  
13:27:19  npm notice shasum:        ae910de4c09cd27e706006664cd3334e22253e40
13:27:19  npm notice integrity:     sha512-kx9I73pfEsQkg[...]bTX2JfwarO+HA==
13:27:19  npm notice total files:   2                                       
13:27:19  npm notice 
13:27:19  npm ERR! code E403
13:27:19  npm ERR! 403 403 Forbidden - PUT https://artifacts.*****.in:443/artifactory/api/npm/npm/@*****%2fpackage-2 - forbidden
13:27:19  npm ERR! 403 In most cases, you or one of your dependencies are requesting
13:27:19  npm ERR! 403 a package version that is forbidden by your security policy.
13:27:19  
13:27:19  npm ERR! A complete log of this run can be found in:
13:27:19  npm ERR!     /home/jenkins/workspace/*****_master/packages/package-2/npm-cache/_logs/2021-01-27T18_27_18_998Z-debug.log
13:27:19  2021-01-27T18:27:19.008Z release-it:shell {
13:27:19    command: 'npm publish dist --tag latest  ',
13:27:19    options: { write: false },
13:27:19    code: 1,
13:27:19    stdout: '',
13:27:19    stderr: 'npm notice \n' +
13:27:19      'npm notice package: @*****/package-2@0.0.1\n' +
13:27:19      'npm notice === Tarball Contents === \n' +
13:27:19      'npm notice 1.1kB package.json\n' +
13:27:19      'npm notice 4.0kB readme.md   \n' +
13:27:19      'npm notice === Tarball Details === \n' +
13:27:19      'npm notice name:          @*****/package-2         \n' +
13:27:19      'npm notice version:       0.0.1                                   \n' +
13:27:19      'npm notice package size:  2.5 kB                                  \n' +
13:27:19      'npm notice unpacked size: 5.0 kB                                  \n' +
13:27:19      'npm notice shasum:        ae910de4c09cd27e706006664cd3334e22253e40\n' +
13:27:19      'npm notice integrity:     sha512-kx9I73pfEsQkg[...]bTX2JfwarO+HA==\n' +
13:27:19      'npm notice total files:   2                                       \n' +
13:27:19      'npm notice \n' +
13:27:19      'npm ERR! code E403\n' +
13:27:19      'npm ERR! 403 403 Forbidden - PUT https://artifacts.*****.in:443/artifactory/api/npm/npm/@*****%2fpackage-2 - forbidden\n' +
13:27:19      'npm ERR! 403 In most cases, you or one of your dependencies are requesting\n' +
13:27:19      'npm ERR! 403 a package version that is forbidden by your security policy.\n' +
13:27:19      '\n' +
13:27:19      'npm ERR! A complete log of this run can be found in:\n' +
13:27:19      'npm ERR!     /home/jenkins/workspace/*****_master/packages/package-2/npm-cache/_logs/2021-01-27T18_27_18_998Z-debug.log\n'
13:27:19  }
13:27:19  2021-01-27T18:27:19.009Z release-it:npm Error: npm notice 
13:27:19  npm notice package: @*****/package-2@0.0.1
13:27:19  npm notice === Tarball Contents === 
13:27:19  npm notice 1.1kB package.json
13:27:19  npm notice 4.0kB readme.md   
13:27:19  npm notice === Tarball Details === 
13:27:19  npm notice name:          @*****/package-2         
13:27:19  npm notice version:       0.0.1                                   
13:27:19  npm notice package size:  2.5 kB                                  
13:27:19  npm notice unpacked size: 5.0 kB                                  
13:27:19  npm notice shasum:        ae910de4c09cd27e706006664cd3334e22253e40
13:27:19  npm notice integrity:     sha512-kx9I73pfEsQkg[...]bTX2JfwarO+HA==
13:27:19  npm notice total files:   2                                       
13:27:19  npm notice 
13:27:19  npm ERR! code E403
13:27:19  npm ERR! 403 403 Forbidden - PUT https://artifacts.*****.in:443/artifactory/api/npm/npm/@*****%2fpackage-2 - forbidden
13:27:19  npm ERR! 403 In most cases, you or one of your dependencies are requesting
13:27:19  npm ERR! 403 a package version that is forbidden by your security policy.
13:27:19  
13:27:19  npm ERR! A complete log of this run can be found in:
13:27:19  npm ERR!     /home/jenkins/workspace/*****_master/packages/package-2/npm-cache/_logs/2021-01-27T18_27_18_998Z-debug.log
13:27:19  
13:27:19      at /home/jenkins/workspace/*****_master/node_modules/release-it/lib/shell.js:69:18
13:27:19      at /home/jenkins/workspace/*****_master/node_modules/shelljs/src/exec.js:127:9
13:27:19      at ChildProcess.exithandler (child_process.js:310:5)
13:27:19      at ChildProcess.emit (events.js:315:20)
13:27:19      at maybeClose (internal/child_process.js:1021:16)
13:27:19      at Socket.<anonymous> (internal/child_process.js:443:11)
13:27:19      at Socket.emit (events.js:315:20)
13:27:19      at Pipe.<anonymous> (net.js:674:12)
13:27:19  2021-01-27T18:27:19.024Z release-it:metrics {
13:27:19    url: 'http://www.google-analytics.com/collect',
13:27:19    statusCode: 200,
13:27:19    statusMessage: 'OK',
13:27:19    payload: 't=exception&exd=Error%3A+npm+notice+'
13:27:19  }
13:27:19  ERROR npm notice 
13:27:19  npm notice package: @*****/package-2@0.0.1
13:27:19  npm notice === Tarball Contents === 
13:27:19  npm notice 1.1kB package.json
13:27:19  npm notice 4.0kB readme.md   
13:27:19  npm notice === Tarball Details === 
13:27:19  npm notice name:          @*****/package-2         
13:27:19  npm notice version:       0.0.1                                   
13:27:19  npm notice package size:  2.5 kB                                  
13:27:19  npm notice unpacked size: 5.0 kB                                  
13:27:19  npm notice shasum:        ae910de4c09cd27e706006664cd3334e22253e40
13:27:19  npm notice integrity:     sha512-kx9I73pfEsQkg[...]bTX2JfwarO+HA==
13:27:19  npm notice total files:   2                                       
13:27:19  npm notice 
13:27:19  npm ERR! code E403
13:27:19  npm ERR! 403 403 Forbidden - PUT https://artifacts.*****.in:443/artifactory/api/npm/npm/@*****%2fpackage-2 - forbidden
13:27:19  npm ERR! 403 In most cases, you or one of your dependencies are requesting
13:27:19  npm ERR! 403 a package version that is forbidden by your security policy.
13:27:19  
13:27:19  npm ERR! A complete log of this run can be found in:
13:27:19  npm ERR!     /home/jenkins/workspace/*****_master/packages/package-2/npm-cache/_logs/2021-01-27T18_27_18_998Z-debug.log
13:27:19  
13:27:19  ERR! error npm notice 
13:27:19  ERR! error npm notice package: @*****/package-2@0.0.1
13:27:19  ERR! error npm notice === Tarball Contents === 
13:27:19  ERR! error npm notice 1.1kB package.json
13:27:19  ERR! error npm notice 4.0kB readme.md   
13:27:19  ERR! error npm notice === Tarball Details === 
13:27:19  ERR! error npm notice name:          @*****/package-2         
13:27:19  ERR! error npm notice version:       0.0.1                                   
13:27:19  ERR! error npm notice package size:  2.5 kB                                  
13:27:19  ERR! error npm notice unpacked size: 5.0 kB                                  
13:27:19  ERR! error npm notice shasum:        ae910de4c09cd27e706006664cd3334e22253e40
13:27:19  ERR! error npm notice integrity:     sha512-kx9I73pfEsQkg[...]bTX2JfwarO+HA==
13:27:19  ERR! error npm notice total files:   2                                       
13:27:19  ERR! error npm notice 
13:27:19  ERR! error npm ERR! code E403
13:27:19  ERR! error npm ERR! 403 403 Forbidden - PUT https://artifacts.*****.in:443/artifactory/api/npm/npm/@*****%2fpackage-2 - forbidden
13:27:19  ERR! error npm ERR! 403 In most cases, you or one of your dependencies are requesting
13:27:19  ERR! error npm ERR! 403 a package version that is forbidden by your security policy.
13:27:19  ERR! error 
13:27:19  ERR! error npm ERR! A complete log of this run can be found in:
13:27:19  ERR! error npm ERR!     /home/jenkins/workspace/*****_master/packages/package-2/npm-cache/_logs/2021-01-27T18_27_18_998Z-debug.log
13:27:19  ERR! error 
```

**Comment by KumarSumitD** [comment]
The 403 error you see is because it is trying to publish the same version.

**Comment by KumarSumitD** [comment]
@webpro

**Comment by webpro** [comment]
Not sure if you already do this, but it looks like release-it is running from the root of the project, so it looks at the sibling `package.json` next to it, etc. It doesn't support monorepos. You can `cd` into "packages/package2" and run release-it from there.

**Comment by webpro** [comment]
Forgot to say, maybe https://github.com/rwjblue/release-it-yarn-workspaces is interesting for you.

**Comment by KumarSumitD** [comment]
Thanks @webpro for the reply. 
I am running release-it from the actual package only and not from root.
Also regarding the release-it-yarn-workspaces, looks like it is only for yarn and not npm. But I will give it a look.
In the mean time since i was blocked, I used npm commands to tag and publish.

**Comment by KumarSumitD** [comment]
As @webpro confirmed, release-it does not support monorepos and the alternative solution also did not work. May be it needs a new feature for release-it. 
Meanwhile I am closing the ticket.
