### ISSUE TITLE
Introduction of CI_JOB_TOKEN breaks existing CI pipelines that use GITLAB_TOKEN

### ISSUE THREAD

**Issue by fholzer** [release-it/release-it#743]
I observed pipelines breaking due to f1b1144dba107747b19ba55138eded9282ccb301, as the GitLab plugin uses the header name `Job-Token`, but instead of using the environment variable `CI_JOB_TOKEN` as header value, it uses `GITLAB_TOKEN`.

In order to maintain backwards compatibility, release-it should use the new `Job-Token` only if `GITLAB_TOKEN` is unset. otherwise release-it will break for everyone that was using `GITLAB_TOKEN` in the past and just upgrade to 14+.

The line in the changelog reads

    Use Job-Token over Private-Token header if CI_JOB_TOKEN is set

But when looking at the code, the presence of the `CI_JOB_TOKEN` is used only to determine the header name to use for requests send to GitLab, but not the header value. Not sure if this is by design or not. One would have to set `gitlab.tokenRef = "CI_JOB_TOKEN"` in release-it's config for it to properly use `CI_JOB_TOKEN` if I understood the code correctly.

Regards,
Ferdinand

**Comment by fholzer** [comment]
>One would have to set gitlab.tokenRef = "CI_JOB_TOKEN" in release-it's config for it to properly use CI_JOB_TOKEN if I understood the code correctly.

Just tried that, and seems it doesn't work either. For now, I'll downgrade to ^13

**Comment by fholzer** [comment]
This is what I got on `release-it@latest`, with `GITLAB_TOKEN` set, and `gitlab.tokenRef` not set.
```
2021-02-18T09:41:25.831Z release-it:config {
  system: { 'release-it': '14.4.0', node: 'v14.15.0', os: 'Linux 3.10' }
}
[...]
2021-02-18T09:41:26.637Z release-it:gitlab { url: 'https://gitlab.domain.REDACTED/api/v4/user', method: 'GET' }
2021-02-18T09:41:26.685Z release-it:gitlab HTTPError: Response code 401 (Unauthorized)
    at Request.<anonymous> (/builds/project/path/REDACTED/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
ERROR Could not authenticate with GitLab using environment variable "GITLAB_TOKEN".
```

Looking at https://github.com/release-it/release-it/blob/14.4.0/lib/plugin/gitlab/GitLab.js, and knowing that our GitLab runner sets `CI_JOB_TOKEN`, it seems like release-it sends a request with header `"Job-Token": "$GITLAB_TOKEN"` which of course won't work. Even setting `gitlab.tokenRef = "CI_JOB_TOKEN"` in my release-it configuration didn't work, though I didn't dig deeper on that as I'm not even sure what permissions exactly this CI_JOB_TOKEN has.

What do you think about this @niekvandael? I think you requested the use of Job-Token header in #736. How did you get this to work properly for you?

**Comment by fholzer** [comment]
I think this boils down to the fact that when `Job-Token` is used as header name, then it must be set to the value of the `CI_JOB_TOKEN` environment variable. Otherwise the `isAuthenticated` call fails. Though I would suggest to give users an option to not use CI_JOB_TOKEN, as the CI_JOB_TOKEN only has limited permissions. 
From [official docs](https://docs.gitlab.com/ee/user/project/new_ci_build_permissions_model.html):
````
The job token has these limitations:

Not all APIs allow job tokens for authentication. See this list for available endpoints.
The token is valid only while the pipeline job runs. Once the job finishes, the token can’t be used for authentication.
````
[List of permissions granted to Job Tokens](https://docs.gitlab.com/ee/api/README.html#gitlab-ci-job-token)

Specifically `write_repository` doesn't seem to be among the permissions, if I read the docs correctly. This means release-it can't create release commits and push them to the repository. In light of that, f1b1144 seems to be a breaking change. 🤔

**Comment by webpro** [comment]
Thanks for digging into this, @fholzer.

The implementation is indeed not great: switching the header name automatically, but not the value. This I will fix shortly.

Regarding the limited permissions, that should not be a problem. The `isAuthenticated` and `isCollaborator` can be skipped when the CI token is set (the GitHub plugin does the same on GitHub Actions). For the Git commands the token is not used.

So, with release-it v14.4.0, the following config should get you through:

```json
{
  "gitlab": {
    "tokenRef": "CI_JOB_TOKEN",
    "skipChecks": true
  }
}
```

This will skip the authentication and collaborator checks. It would help me a lot if you could verify if this assumption indeed works. I don't have an environment available to verify this myself right now.

**Comment by webpro** [comment]
From [v14.4.1](https://github.com/release-it/release-it/releases/tag/14.4.1), the `gitlab.tokenHeader` and `gitlab.tokenRef` need to be explicitly configured (e.g. `Job-Token` and `CI_JOB_TOKEN`, respectively). This should fix the breaking change (as the default values are like before v14.4.0), and support the use-case in #736 (cc @niekvandael).

**Comment by fholzer** [comment]
Thanks for the quick response to this. I tested my pre-14.4.0 config now on 14.4.1:
````
[...]
"gitlab": {
  "release": true
}
[...]
````
using just the GITLAB_TOKEN CI variable. This works without issues again. Thank you.

When I tried testing the new method using CI_JOB_TOKEN though, it seems there is an issue with release-it creating the gitlab release via the API. We're on GitLab version 13.8.3-ee, the runner version is 13.8.0 (and according to [Debug logging](https://docs.gitlab.com/ee/ci/variables/#enable-debug-logging) the runner did provide the CI_JOB_TOKEN). 
Release-it debug output:
````
DEBUG=release-it:* npx release-it --ci --disable-metrics  -VV --npm.skipChecks=true
2021-02-19T12:08:59.186Z release-it:config {
  cosmiconfig: {
    config: {
      git: [Object],
      gitlab: [Object],
      npm: [Object],
      plugins: [Object]
    },
    filepath: '/builds/project/path/REDACTED/package.json'
  }
}
2021-02-19T12:08:59.189Z release-it:config {
  system: { 'release-it': '14.4.1', node: 'v14.15.0', os: 'Linux 3.10' }
}
2021-02-19T12:08:59.190Z release-it:config {
  _: [],
  ci: true,
  'disable-metrics': true,
  verbose: 2,
  npm: {
    skipChecks: 'true',
    publish: false,
    publishPath: '.',
    tag: null,
    otp: null,
    ignoreVersion: false,
    timeout: 10
  },
  increment: undefined,
  git: {
    commitMessage: 'chore(release): Release v${version}',
    pushArgs: [ '--follow-tags' ],
    changelog: 'git log --pretty=format:"* %s (%h)" ${from}...${to}',
    requireCleanWorkingDir: true,
    requireBranch: false,
    requireUpstream: true,
    requireCommits: false,
    addUntrackedFiles: false,
    commit: true,
    commitArgs: [],
    tag: true,
    tagName: null,
    tagAnnotation: 'Release ${version}',
    tagArgs: [],
    push: true,
    pushRepo: ''
  },
  gitlab: {
    release: true,
    tokenRef: 'CI_JOB_TOKEN',
    skipChecks: true,
    releaseName: 'Release ${version}',
    releaseNotes: null,
    tokenHeader: 'Private-Token',
    assets: null,
    origin: null
  },
  plugins: {
    '@release-it/conventional-changelog': { preset: 'angular', infile: 'CHANGELOG.md' }
  },
  hooks: {},
  github: {
    release: false,
    releaseName: 'Release ${version}',
    releaseNotes: null,
    preRelease: false,
    draft: false,
    tokenRef: 'GITHUB_TOKEN',
    assets: null,
    host: null,
    timeout: 0,
    proxy: null,
    skipChecks: false
  },
  isUpdate: false,
  version: {
    increment: undefined,
    isPreRelease: false,
    preReleaseId: undefined
  }
}
2021-02-19T12:08:59.329Z release-it:config {
  'conventional-changelog': { preset: 'angular', infile: 'CHANGELOG.md' }
}
2021-02-19T12:08:59.330Z release-it:plugins {
  namespace: 'conventional-changelog',
  options: { preset: 'angular', infile: 'CHANGELOG.md', tagName: null }
}
2021-02-19T12:08:59.332Z release-it:plugins {
  namespace: 'npm',
  options: {
    skipChecks: 'true',
    publish: false,
    publishPath: '.',
    tag: null,
    otp: null,
    ignoreVersion: false,
    timeout: 10
  }
}
2021-02-19T12:08:59.333Z release-it:plugins {
  namespace: 'gitlab',
  options: {
    release: true,
    tokenRef: 'CI_JOB_TOKEN',
    skipChecks: true,
    releaseName: 'Release ${version}',
    releaseNotes: null,
    tokenHeader: 'Private-Token',
    assets: null,
    origin: null,
    tagName: null,
    pushRepo: '',
    changelog: 'git log --pretty=format:"* %s (%h)" ${from}...${to}',
    isUpdate: false
  }
}
2021-02-19T12:08:59.335Z release-it:plugins {
  namespace: 'git',
  options: {
    commitMessage: 'chore(release): Release v${version}',
    pushArgs: [ '--follow-tags' ],
    changelog: 'git log --pretty=format:"* %s (%h)" ${from}...${to}',
    requireCleanWorkingDir: true,
    requireBranch: false,
    requireUpstream: true,
    requireCommits: false,
    addUntrackedFiles: false,
    commit: true,
    commitArgs: [],
    tag: true,
    tagName: null,
    tagAnnotation: 'Release ${version}',
    tagArgs: [],
    push: true,
    pushRepo: '',
    isUpdate: false
  }
}
$ git diff --quiet HEAD
2021-02-19T12:08:59.352Z release-it:shell {
  command: 'git diff --quiet HEAD',
  options: { write: false },
  code: 0,
  stdout: '',
  stderr: ''
}
$ git rev-parse --abbrev-ref HEAD
master
master
2021-02-19T12:08:59.366Z release-it:shell {
  command: 'git rev-parse --abbrev-ref HEAD',
  options: { write: false },
  code: 0,
  stdout: 'master',
  stderr: ''
}
$ git config --get branch.master.remote
origin
origin
2021-02-19T12:08:59.381Z release-it:shell {
  command: 'git config --get branch.master.remote',
  options: { write: false },
  code: 0,
  stdout: 'origin',
  stderr: ''
}
$ git remote get-url origin
error: Unknown subcommand: get-url
usage: git remote [-v | --verbose]
   or: git remote add [-t <branch>] [-m <master>] [-f] [--tags|--no-tags] [--mirror=<fetch|push>] <name> <url>
   or: git remote rename <old> <new>
   or: git remote remove <name>
   or: git remote set-head <name> (-a | -d | <branch>)
   or: git remote [-v | --verbose] show [-n] <name>
   or: git remote prune [-n | --dry-run] <name>
   or: git remote [-v | --verbose] update [-p | --prune] [(<group> | <remote>)...]
   or: git remote set-branches [--add] <name> <branch>...
   or: git remote set-url [--push] <name> <newurl> [<oldurl>]
   or: git remote set-url --add <name> <newurl>
error: Unknown subcommand: get-url
usage: git remote [-v | --verbose]
   or: git remote add [-t <branch>] [-m <master>] [-f] [--tags|--no-tags] [--mirror=<fetch|push>] <name> <url>
   or: git remote rename <old> <new>
   or: git remote remove <name>
   or: git remote set-head <name> (-a | -d | <branch>)
   or: git remote [-v | --verbose] show [-n] <name>
   or: git remote prune [-n | --dry-run] <name>
   or: git remote [-v | --verbose] update [-p | --prune] [(<group> | <remote>)...]
   or: git remote set-branches [--add] <name> <branch>...
   or: git remote set-url [--push] <name> <newurl> [<oldurl>]
   or: git remote set-url --add <name> <newurl>
   or: git remote set-url --delete <name> <url>
    -v, --verbose         be verbose; must be placed before a subcommand
or: git remote set-url --delete <name> <url>
    -v, --verbose         be verbose; must be placed before a subcommand
2021-02-19T12:08:59.396Z release-it:shell {
  command: 'git remote get-url origin',
  options: { write: false },
  code: 129,
  stdout: '',
  stderr: 'error: Unknown subcommand: get-url\n' +
    'usage: git remote [-v | --verbose]\n' +
    '   or: git remote add [-t <branch>] [-m <master>] [-f] [--tags|--no-tags] [--mirror=<fetch|push>] <name> <url>\n' +
    '   or: git remote rename <old> <new>\n' +
    '   or: git remote remove <name>\n' +
    '   or: git remote set-head <name> (-a | -d | <branch>)\n' +
    '   or: git remote [-v | --verbose] show [-n] <name>\n' +
    '   or: git remote prune [-n | --dry-run] <name>\n' +
    '   or: git remote [-v | --verbose] update [-p | --prune] [(<group> | <remote>)...]\n' +
    '   or: git remote set-branches [--add] <name> <branch>...\n' +
    '   or: git remote set-url [--push] <name> <newurl> [<oldurl>]\n' +
    '   or: git remote set-url --add <name> <newurl>\n' +
    '   or: git remote set-url --delete <name> <url>\n' +
    '\n' +
    '    -v, --verbose         be verbose; must be placed before a subcommand\n' +
    '\n'
}
$ git config --get remote.origin.url
git@gitlab.domain.REDACTED:project/path/REDACTED.git
git@gitlab.domain.REDACTED:project/path/REDACTED.git
2021-02-19T12:08:59.407Z release-it:shell {
  command: 'git config --get remote.origin.url',
  options: { write: false },
  code: 0,
  stdout: 'git@gitlab.domain.REDACTED:project/path/REDACTED.git',
  stderr: ''
}
$ git fetch
2021-02-19T12:08:59.679Z release-it:shell { command: 'git fetch', options: {}, code: 0, stdout: '', stderr: '' }
$ git describe --tags --match=* --abbrev=0
0.1.9
0.1.9
2021-02-19T12:08:59.697Z release-it:shell {
  command: 'git describe --tags --match=* --abbrev=0',
  options: { write: false },
  code: 0,
  stdout: '0.1.9',
  stderr: ''
}
2021-02-19T12:08:59.698Z release-it:config { latestTag: '0.1.9' }
$ git symbolic-ref HEAD
refs/heads/master
refs/heads/master
2021-02-19T12:08:59.713Z release-it:shell {
  command: 'git symbolic-ref HEAD',
  options: { write: false },
  code: 0,
  stdout: 'refs/heads/master',
  stderr: ''
}
$ git for-each-ref --format="%(upstream:short)" refs/heads/master
origin/master
origin/master
2021-02-19T12:08:59.728Z release-it:shell {
  command: 'git for-each-ref --format="%(upstream:short)" refs/heads/master',
  options: { write: false },
  code: 0,
  stdout: 'origin/master',
  stderr: ''
}
2021-02-19T12:08:59.728Z release-it:config {
  repo: {
    host: 'gitlab.domain.REDACTED',
    owner: 'project/path',
    project: 'cicd-test2',
    protocol: 'ssh',
    remote: 'git@gitlab.domain.REDACTED:project/path/REDACTED.git',
    repository: 'project/path/REDACTED'
  }
}
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git config --get branch.master.remote  [cached]
$ git remote get-url origin  [cached]
$ git config --get remote.origin.url  [cached]
$ git fetch  [cached]
$ git describe --tags --match=* --abbrev=0  [cached]
2021-02-19T12:08:59.735Z release-it:config { latestTag: '0.1.9' }
2021-02-19T12:08:59.736Z release-it:conventional-changelog {
  increment: undefined,
  latestVersion: '0.1.9',
  isPreRelease: false,
  preReleaseId: undefined
}
2021-02-19T12:08:59.805Z release-it:conventional-changelog {
  err: null,
  result: {
    level: 2,
    reason: 'There are 0 BREAKING CHANGES and 0 features',
    releaseType: 'patch'
  }
}
2021-02-19T12:08:59.920Z release-it:conventional-changelog Your git-log command is:
git log --format=%B%n-hash-%n%H%n-gitTags-%n%d%n-committerDate-%n%ci%n------------------------ >8 ------------------------ 0.1.9 --no-merges
2021-02-19T12:08:59.928Z release-it:conventional-changelog Your git-log command is:
git log --format=%B%n-hash-%n%H%n-gitTags-%n%d%n-committerDate-%n%ci%n------------------------ >8 ------------------------ 0.1.9..HEAD --no-merges
2021-02-19T12:09:00.001Z release-it:config {
  name: 'test-package',
  latestVersion: '0.1.9',
  version: undefined,
  changelog: '## [0.1.10](https://gitlab.domain.REDACTED/project/path/REDACTED/compare/0.1.9...0.1.10) (2021-02-19)'
}
🚀 Let's release test-package (currently at 0.1.9)
Changelog:
## [0.1.10](https://gitlab.domain.REDACTED/project/path/REDACTED/compare/0.1.9...0.1.10) (2021-02-19)
2021-02-19T12:09:00.003Z release-it:config { version: '0.1.10', isPreRelease: false, preReleaseId: null }
$ npm version 0.1.10 --no-git-tag-version
v0.1.10
v0.1.10
2021-02-19T12:09:00.428Z release-it:shell {
  command: 'npm version 0.1.10 --no-git-tag-version',
  options: {},
  code: 0,
  stdout: 'v0.1.10',
  stderr: ''
}
2021-02-19T12:09:00.429Z release-it:config { tagName: '0.1.10' }
2021-02-19T12:09:00.430Z release-it:config { tagName: '0.1.10' }
$ Writing changelog to CHANGELOG.md
$ git status --short --untracked-files=no
 M CHANGELOG.md
 M package.json
M CHANGELOG.md
 M package.json
2021-02-19T12:09:00.470Z release-it:shell {
  command: 'git status --short --untracked-files=no',
  options: { write: false },
  code: 0,
  stdout: 'M CHANGELOG.md\n M package.json',
  stderr: ''
}
Changeset:
M CHANGELOG.md
 M package.json
$ git add . --update
2021-02-19T12:09:00.488Z release-it:shell {
  command: [ 'git', 'add', '.', '--update' ],
  options: {},
  stdout: '',
  stderr: ''
}
$ git commit --message chore(release): Release v0.1.10
[master 2903206] chore(release): Release v0.1.10
 2 files changed, 3 insertions(+), 1 deletion(-)
2021-02-19T12:09:00.512Z release-it:shell {
  command: [ 'git', 'commit', '--message', 'chore(release): Release v0.1.10' ],
  options: {},
  stdout: '[master 2903206] chore(release): Release v0.1.10\n' +
    ' 2 files changed, 3 insertions(+), 1 deletion(-)',
  stderr: ''
}
$ git tag --annotate --message Release 0.1.10 0.1.10
2021-02-19T12:09:00.525Z release-it:shell {
  command: [
    'git',
    'tag',
    '--annotate',
    '--message',
    'Release 0.1.10',
    '0.1.10'
  ],
  options: {},
  stdout: '',
  stderr: ''
}
$ git symbolic-ref HEAD  [cached]
$ git for-each-ref --format="%(upstream:short)" refs/heads/master  [cached]
$ git push --follow-tags
2021-02-19T12:09:01.393Z release-it:shell {
  command: [ 'git', 'push', '--follow-tags' ],
  options: {},
  stdout: '',
  stderr: 'warning: push.default is unset; its implicit value is changing in\n' +
    "Git 2.0 from 'matching' to 'simple'. To squelch this message\n" +
    'and maintain the current behavior after the default changes, use:\n' +
    '\n' +
    '  git config --global push.default matching\n' +
    '\n' +
    'To squelch this message and adopt the new behavior now, use:\n' +
    '\n' +
    '  git config --global push.default simple\n' +
    '\n' +
    "See 'git help config' and search for 'push.default' for further information.\n" +
    "(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode\n" +
    "'current' instead of 'simple' if you sometimes use older versions of Git)\n" +
    '\n' +
    'To git@gitlab.domain.REDACTED:project/path/REDACTED.git\n' +
    '   45880ec..2903206  master -> master\n' +
    ' * [new tag]         0.1.10 -> 0.1.10'
}
! gitlab releases#createRelease "Release 0.1.10" (0.1.10)
2021-02-19T12:09:01.396Z release-it:gitlab {
  url: 'https://gitlab.domain.REDACTED/api/v4/projects/project%2Fpath%2Fcicd-test2/releases',
  json: {
    name: 'Release 0.1.10',
    tag_name: '0.1.10',
    description: '## [0.1.10](https://gitlab.domain.REDACTED/project/path/REDACTED/compare/0.1.9...0.1.10) (2021-02-19)'
  }
}
2021-02-19T12:09:01.485Z release-it:gitlab HTTPError: Response code 401 (Unauthorized)
    at Request.<anonymous> (/builds/project/path/REDACTED/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
ERROR Response code 401 (Unauthorized)
````
Even though there's some warning with git cli output (due to old version) this is nicely handled by release-it and there's no issues with any of the git operations. Though the GitLab release can't be created. According to official docs, though, the using the CI_JOB_TOKEN for the release API should work fine 🤷‍♂️

**Comment by webpro** [comment]
You also need to explicitly set the `gitlab.tokenHeader` to `Job-Token` (I see `tokenHeader: 'Private-Token'` in your config, the default value). Sorry I wasn't more clear about this.

**Comment by fholzer** [comment]
You're right, I though about that when I initially read you response, but then forgot to add it. Added now, still something isn't right.
````
[...]
2021-02-19T13:35:46.894Z release-it:plugins {
  namespace: 'gitlab',
  options: {
    release: true,
    tokenRef: 'CI_JOB_TOKEN',
    tokenHeader: 'Private-Token',
    skipChecks: true,
    releaseName: 'Release ${version}',
    releaseNotes: null,
    assets: null,
    origin: null,
    tagName: null,
    pushRepo: '',
    changelog: 'git log --pretty=format:"* %s (%h)" ${from}...${to}',
    isUpdate: false
  }
}
[...]
! gitlab releases#createRelease "Release 0.1.11" (0.1.11)
2021-02-19T13:35:48.442Z release-it:gitlab {
  url: 'https://gitlab.domain.REDACTED/api/v4/projects/project%2Fpath%2Fcicd-test2/releases',
  json: {
    name: 'Release 0.1.11',
    tag_name: '0.1.11',
    description: '## [0.1.11](https://gitlab.domain.REDACTED/project/path/cicd-test2/compare/0.1.10...0.1.11) (2021-02-19)'
  }
}
2021-02-19T13:35:48.502Z release-it:gitlab HTTPError: Response code 401 (Unauthorized)
    at Request.<anonymous> (/builds/project/path/cicd-test2/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
ERROR Response code 401 (Unauthorized)
````
Will try to dig a little deeper over the weekend.

**Comment by fholzer** [comment]
Seems the remaining issue I had was due to misconfiguration of our .gitlab-ci.yml file wrongly overriding the GITLAB_TOKEN variable. So all good now.
