### ISSUE TITLE
Invalid Version: null

### ISSUE THREAD

**Issue by 4n70w4** [release-it/release-it#746]
Hi!

```
release-it --version
```

```
v14.4.1
```

```json
{
  "increment": true,
  "pkgFiles": ["composer.json"],
  "git": {
    "requireCleanWorkingDir": false,
    "commit": false,
    "tag": true,
    "push": false
  },
  "npm": false
}
```

```
release-it --config r.json
```

```
🚀 Let's release collector (currently at null)


Empty changelog

? Select increment (next version): (Use arrow keys)
❯ patch (null)
  minor (null)
  major (null)
  prepatch (null)
  preminor (null)
  premajor (null)
  Other, please specify...
```

```
? Select increment (next version): Other, please specify...
? Please enter a valid version: 1.1.(node:2141) UnhandledPromiseRejectionWarning: TypeError: Invalid Version: null
    at new SemVer (/usr/local/lib/node_modules/release-it/node_modules/semver/classes/semver.js:38:13)
    at compare (/usr/local/lib/node_modules/release-it/node_modules/semver/functions/compare.js:3:32)
    at Object.gt (/usr/local/lib/node_modules/release-it/node_modules/semver/functions/gt.js:2:29)
    at input (/usr/local/lib/node_modules/release-it/lib/plugin/version/Version.js:33:33)
    at InputPrompt.render (/usr/local/lib/node_modules/release-it/node_modules/inquirer/lib/prompts/input.js:58:18)
    at InputPrompt.onKeypress (/usr/local/lib/node_modules/release-it/node_modules/inquirer/lib/prompts/input.js:109:10)
    at SafeSubscriber._next (/usr/local/lib/node_modules/release-it/node_modules/rxjs/internal/Observable.js:66:21)
    at SafeSubscriber.__tryOrUnsub (/usr/local/lib/node_modules/release-it/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/usr/local/lib/node_modules/release-it/node_modules/rxjs/internal/Subscriber.js:143:22)
    at Subscriber._next (/usr/local/lib/node_modules/release-it/node_modules/rxjs/internal/Subscriber.js:89:26)
(node:2141) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2141) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
? Please enter a valid version: 1.1.1.l
>> The version must follow the semver standard.
```

**Comment by webpro** [comment]
* The `increment` should be used differently:
  * omit it,
  * use `patch`, `minor` or `major`,
  * or specify the next (semver) version.
* The [`pkgFiles` option was removed in v11](https://github.com/release-it/release-it/blob/master/CHANGELOG.md#v11). You can use https://github.com/release-it/bumper for this.
