### ISSUE TITLE
Document Access Scopes Needed for GITHUB_TOKEN

### ISSUE THREAD

**Issue by stephenhmarsh** [release-it/release-it#750]
Hi. Great package, thanks to the maintainers. Similar to https://github.com/release-it/release-it/issues/172#issuecomment-362814345 , I was getting lot's of errors related to 404's.

First, this one:

```
octokit users#getAuthenticated
request {
  method: 'GET',
  baseUrl: 'https://api.github.com',
  headers: {
    accept: 'application/vnd.github.v3+json',
    'user-agent': 'release-it/14.5.0 octokit-rest.js/18.3.5 octokit-core.js/3.2.5 Node.js/15.12.0 (linux; x64)'
  },
  mediaType: { format: '', previews: [] },
  request: { timeout: 0, hook: [Function: bound bound register] },
  url: '/user'
}
GET /user - 200 in 69ms
octokit repos#checkCollaborator (stephenhmarsh)
request {
  method: 'GET',
  baseUrl: 'https://api.github.com',
  headers: {
    accept: 'application/vnd.github.v3+json',
    'user-agent': 'release-it/14.5.0 octokit-rest.js/18.3.5 octokit-core.js/3.2.5 Node.js/15.12.0 (linux; x64)'
  },
  mediaType: { format: '', previews: [] },
  request: { timeout: 0, hook: [Function: bound bound register] },
  url: '/repos/{owner}/{repo}/collaborators/{username}',
  owner: 'metmuseum',
  repo: 'Marble',
  username: 'stephenhmarsh'
}
GET /repos/metmuseum/Marble/collaborators/stephenhmarsh - 404 in 67ms
  release-it:github HttpError: Not Found
  release-it:github     at /home/circleci/project/node_modules/@octokit/request/dist-node/index.js:66:23
  release-it:github     at processTicksAndRejections (node:internal/process/task_queues:94:5)
  release-it:github     at async GitHub.isCollaborator (/home/circleci/project/node_modules/release-it/lib/plugin/github/GitHub.js:93:7)
  release-it:github     at async GitHub.init (/home/circleci/project/node_modules/release-it/lib/plugin/github/GitHub.js:53:15)
  release-it:github     at async runLifeCycleHook (/home/circleci/project/node_modules/release-it/lib/tasks.js:50:28)
  release-it:github     at async runTasks (/home/circleci/project/node_modules/release-it/lib/tasks.js:61:7) +0ms
  release-it:metrics {
  release-it:metrics   url: 'http://www.google-analytics.com/collect',
  release-it:metrics   statusCode: 200,
  release-it:metrics   statusMessage: 'OK',
  release-it:metrics   payload: 't=exception&exd=Error%3A+User+stephenhmarsh+is+not+a+collaborator+for+metmuseum%2FMarble.'
  release-it:metrics } +2s
ERROR User stephenhmarsh is not a collaborator for metmuseum/Marble.
Documentation: https://git.io/release-it-github

```

Then, if I set `github.disableChecks` to `true` it would error out later:

```
! octokit repos.createRelease "Release 0.11.3" (0.11.3)
  release-it:github {
  release-it:github   owner: 'metmuseum',
  release-it:github   repo: 'Marble',
  release-it:github   tag_name: '0.11.3',
  release-it:github   name: 'Release 0.11.3',
  release-it:github   body: '* disable github checks to debug the later 404 (37e8b03)\n' +
  release-it:github     '* more debugging code (5051d27)\n' +
  release-it:github     '* add some more flags to release-it command to see if i can debug this weird 404 (9f15db1)',
  release-it:github   draft: false,
  release-it:github   prerelease: false
  release-it:github } +0ms
request {
  method: 'POST',
  baseUrl: 'https://api.github.com',
  headers: {
    accept: 'application/vnd.github.v3+json',
    'user-agent': 'release-it/14.5.0 octokit-rest.js/18.3.5 octokit-core.js/3.2.5 Node.js/15.12.0 (linux; x64)'
  },
  mediaType: { format: '', previews: [] },
  request: { timeout: 0, hook: [Function: bound bound register] },
  url: '/repos/{owner}/{repo}/releases',
  owner: 'metmuseum',
  repo: 'Marble',
  tag_name: '0.11.3',
  name: 'Release 0.11.3',
  body: '* disable github checks to debug the later 404 (37e8b03)\n' +
    '* more debugging code (5051d27)\n' +
    '* add some more flags to release-it command to see if i can debug this weird 404 (9f15db1)',
  draft: false,
  prerelease: false
}
POST /repos/metmuseum/Marble/releases - 404 in 77ms

  release-it:github HttpError: Not Found
  release-it:github     at /home/circleci/project/node_modules/@octokit/request/dist-node/index.js:66:23
  release-it:github     at processTicksAndRejections (node:internal/process/task_queues:94:5)
  release-it:github     at async /home/circleci/project/node_modules/release-it/lib/plugin/github/GitHub.js:215:26
  release-it:github     at async GitHub.release (/home/circleci/project/node_modules/release-it/lib/plugin/github/GitHub.js:110:7)
  release-it:github     at async runLifeCycleHook (/home/circleci/project/node_modules/release-it/lib/tasks.js:50:28)
  release-it:github     at async runTasks (/home/circleci/project/node_modules/release-it/lib/tasks.js:102:9) +84ms
  release-it:metrics {
  release-it:metrics   url: 'http://www.google-analytics.com/collect',
  release-it:metrics   statusCode: 200,
  release-it:metrics   statusMessage: 'OK',
  release-it:metrics   payload: 't=exception&exd=Error%3A+404+%28Not+Found%29'
  release-it:metrics } +4s
ERROR 404 (Not Found)
```

I have temporarily "solved" the problem by creating a new personal access token that has permission to ALL scopes.  I would love to see the docs have accurate info, here.

**Comment by webpro** [comment]
So if I understand correctly, and reading the linked issue, for repos in an organization, the `admin:org_hook` is required. Otherwise you get this:

```
GET /repos/metmuseum/Marble/collaborators/stephenhmarsh - 404 in 67ms
```

Could you please try/confirm which token exactly is required in which scenario? So I can document accordingly.

The following error is probably from the tag that does not exist yet when doing a release. Maybe you disabled `git.tag` when debugging this issue:

```
POST /repos/metmuseum/Marble/releases - 404 in 77ms
```

**Comment by stephenhmarsh** [comment]
Ah sorry, I actually meant _I'm not sure_ what scopes _are_ needed.  If I find the time, I will certainly try to figure it out by process of elimination, but in the meantime I was hoping someone out there might already just know.

It looks like like `git.tag` was `true`.  Here is the full logs when from I got the `POST /repos/metmuseum/Marble/releases` 404:

```

> @metmuseum/marble@0.11.2 release
> release-it "patch" "--ci" "-VV" "--no-git.requireUpstream" "--set-upstream" "origin" "main"

  release-it:config {
  release-it:config   cosmiconfig: {
  release-it:config     config: { git: [Object], github: [Object], npm: [Object] },
  release-it:config     filepath: '/home/circleci/project/.release-it.json'
  release-it:config   }
  release-it:config } +0ms
  release-it:config {
  release-it:config   system: { 'release-it': '14.5.0', node: 'v15.12.0', os: 'Linux 4.15' }
  release-it:config } +4ms
  release-it:config {
  release-it:config   _: [ 'patch', 'main' ],
  release-it:config   ci: true,
  release-it:config   verbose: 2,
  release-it:config   git: {
  release-it:config     requireUpstream: false,
  release-it:config     commitMessage: 'Release ${version} [skip ci]',
  release-it:config     changelog: 'git log --pretty=format:"* +0ms (%h)" ${from}...${to}',
  release-it:config     requireCleanWorkingDir: true,
  release-it:config     requireBranch: false,
  release-it:config     requireCommits: false,
  release-it:config     addUntrackedFiles: false,
  release-it:config     commit: true,
  release-it:config     commitArgs: [],
  release-it:config     tag: true,
  release-it:config     tagName: null,
  release-it:config     tagAnnotation: 'Release ${version}',
  release-it:config     tagArgs: [],
  release-it:config     push: true,
  release-it:config     pushArgs: [ '--follow-tags' ],
  release-it:config     pushRepo: ''
  release-it:config   },
  release-it:config   'set-upstream': 'origin',
  release-it:config   increment: 'patch',
  release-it:config   github: {
  release-it:config     release: true,
  release-it:config     skipChecks: true,
  release-it:config     releaseName: 'Release ${version}',
  release-it:config     releaseNotes: null,
  release-it:config     preRelease: false,
  release-it:config     draft: false,
  release-it:config     tokenRef: 'GITHUB_TOKEN',
  release-it:config     assets: null,
  release-it:config     host: null,
  release-it:config     timeout: 0,
  release-it:config     proxy: null
  release-it:config   },
  release-it:config   npm: {
  release-it:config     publish: false,
  release-it:config     publishPath: '.',
  release-it:config     publishArgs: [],
  release-it:config     tag: null,
  release-it:config     otp: null,
  release-it:config     ignoreVersion: false,
  release-it:config     skipChecks: false,
  release-it:config     timeout: 10
  release-it:config   },
  release-it:config   hooks: {},
  release-it:config   gitlab: {
  release-it:config     release: false,
  release-it:config     releaseName: 'Release ${version}',
  release-it:config     releaseNotes: null,
  release-it:config     tokenRef: 'GITLAB_TOKEN',
  release-it:config     tokenHeader: 'Private-Token',
  release-it:config     assets: null,
  release-it:config     origin: null,
  release-it:config     skipChecks: false
  release-it:config   },
  release-it:config   isUpdate: false,
  release-it:config   version: { increment: 'patch', isPreRelease: false, preReleaseId: undefined }
  release-it:config }
  release-it:plugins {
  release-it:plugins   namespace: 'npm',
  release-it:plugins   options: {
  release-it:plugins     publish: false,
  release-it:plugins     publishPath: '.',
  release-it:plugins     publishArgs: [],
  release-it:plugins     tag: null,
  release-it:plugins     otp: null,
  release-it:plugins     ignoreVersion: false,
  release-it:plugins     skipChecks: false,
  release-it:plugins     timeout: 10
  release-it:plugins   }
  release-it:plugins } +0ms
  release-it:plugins {
  release-it:plugins   namespace: 'github',
  release-it:plugins   options: {
  release-it:plugins     release: true,
  release-it:plugins     skipChecks: true,
  release-it:plugins     releaseName: 'Release ${version}',
  release-it:plugins     releaseNotes: null,
  release-it:plugins     preRelease: false,
  release-it:plugins     draft: false,
  release-it:plugins     tokenRef: 'GITHUB_TOKEN',
  release-it:plugins     assets: null,
  release-it:plugins     host: null,
  release-it:plugins     timeout: 0,
  release-it:plugins     proxy: null,
  release-it:plugins     tagName: null,
  release-it:plugins     pushRepo: '',
  release-it:plugins     changelog: 'git log --pretty=format:"* +1ms (%h)" ${from}...${to}',
  release-it:plugins     isUpdate: false
  release-it:plugins   }
  release-it:plugins }
  release-it:plugins {
  release-it:plugins   namespace: 'version',
  release-it:plugins   options: { increment: 'patch', isPreRelease: false, preReleaseId: undefined }
  release-it:plugins } +0ms
  release-it:plugins {
  release-it:plugins   namespace: 'git',
  release-it:plugins   options: {
  release-it:plugins     requireUpstream: false,
  release-it:plugins     commitMessage: 'Release ${version} [skip ci]',
  release-it:plugins     changelog: 'git log --pretty=format:"* +4ms (%h)" ${from}...${to}',
  release-it:plugins     requireCleanWorkingDir: true,
  release-it:plugins     requireBranch: false,
  release-it:plugins     requireCommits: false,
  release-it:plugins     addUntrackedFiles: false,
  release-it:plugins     commit: true,
  release-it:plugins     commitArgs: [],
  release-it:plugins     tag: true,
  release-it:plugins     tagName: null,
  release-it:plugins     tagAnnotation: 'Release ${version}',
  release-it:plugins     tagArgs: [],
  release-it:plugins     push: true,
  release-it:plugins     pushArgs: [ '--follow-tags' ],
  release-it:plugins     pushRepo: '',
  release-it:plugins     isUpdate: false
  release-it:plugins   }
  release-it:plugins }
$ git diff --quiet HEAD
  release-it:metrics {
  release-it:metrics   url: 'http://www.google-analytics.com/collect',
  release-it:metrics   statusCode: 200,
  release-it:metrics   statusMessage: 'OK',
  release-it:metrics   payload: 'v=1&tid=UA-108828841-1&cid=59017540-69f8-4684-a3de-7737268cdfc3&cd1=14.5.0&cd2=v15.12.0&cd3=Linux+4.15&cd4=1&cd5=0&cd6=0&cd7=0&cd8=null&cd9=undefined&cd11=1&cd12=1&cd13=0&cd14=1&cd15=patch&cd16=0&t=event&ec=session&ea=start'
  release-it:metrics } +0ms
  release-it:shell {
  release-it:shell   command: 'git diff --quiet HEAD',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: '',
  release-it:shell   stderr: ''
  release-it:shell } +0ms
$ git rev-parse --abbrev-ref HEAD
main
main
  release-it:shell {
  release-it:shell   command: 'git rev-parse --abbrev-ref HEAD',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'main',
  release-it:shell   stderr: ''
  release-it:shell } +7ms
$ git config --get branch.main.remote
origin
origin
  release-it:shell {
  release-it:shell   command: 'git config --get branch.main.remote',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'origin',
  release-it:shell   stderr: ''
  release-it:shell } +6ms
$ git remote get-url origin
git@github.com:metmuseum/Marble.git
git@github.com:metmuseum/Marble.git
  release-it:shell {
  release-it:shell   command: 'git remote get-url origin',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'git@github.com:metmuseum/Marble.git',
  release-it:shell   stderr: ''
  release-it:shell } +5ms
$ git fetch
Warning: Permanently added the RSA host key for IP address '140.82.113.4' to the list of known hosts.

Warning: Permanently added the RSA host key for IP address '140.82.113.4' to the list of known hosts.
  release-it:shell {
  release-it:shell   command: 'git fetch',
  release-it:shell   options: {},
  release-it:shell   code: 0,
  release-it:shell   stdout: '',
  release-it:shell   stderr: "Warning: Permanently added the RSA host key for IP address '140.82.113.4' to the list of known hosts.\r\n"
  release-it:shell } +316ms
$ git describe --tags --match=* --abbrev=0
0.11.2
0.11.2
  release-it:shell {
  release-it:shell   command: 'git describe --tags --match=* --abbrev=0',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: '0.11.2',
  release-it:shell   stderr: ''
  release-it:shell } +9ms
  release-it:config { latestTag: '0.11.2' } +1s
  release-it:config {
  release-it:config   repo: {
  release-it:config     host: 'github.com',
  release-it:config     owner: 'metmuseum',
  release-it:config     project: 'Marble',
  release-it:config     protocol: 'ssh',
  release-it:config     remote: 'git@github.com:metmuseum/Marble.git',
  release-it:config     repository: 'metmuseum/Marble'
  release-it:config   }
  release-it:config } +0ms
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git config --get branch.main.remote  [cached]
$ git remote get-url origin  [cached]
$ git fetch  [cached]
$ git describe --tags --match=* --abbrev=0  [cached]
  release-it:config { latestTag: '0.11.2' } +2ms
$ git log --pretty=format:"* %s (%h)" 0.11.2...HEAD
* disable github checks to debug the later 404 (37e8b03)
* more debugging code (5051d27)
* add some more flags to release-it command to see if i can debug this weird 404 (9f15db1)* disable github checks to debug the later 404 (37e8b03)
* more debugging code (5051d27)
* add some more flags to release-it command to see if i can debug this weird 404 (9f15db1)
  release-it:shell {
  release-it:shell   command: 'git log --pretty=format:"* +9ms (%h)" 0.11.2...HEAD',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: '* disable github checks to debug the later 404 (37e8b03)\n' +
  release-it:shell     '* more debugging code (5051d27)\n' +
  release-it:shell     '* add some more flags to release-it command to see if i can debug this weird 404 (9f15db1)',
  release-it:shell   stderr: ''
  release-it:shell }
  release-it:config {
  release-it:config   name: '@metmuseum/marble',
  release-it:config   latestVersion: '0.11.2',
  release-it:config   version: '0.11.3',
  release-it:config   changelog: '* disable github checks to debug the later 404 (37e8b03)\n' +
  release-it:config     '* more debugging code (5051d27)\n' +
  release-it:config     '* add some more flags to release-it command to see if i can debug this weird 404 (9f15db1)'
  release-it:config } +8ms
🚀 Let's release @metmuseum/marble (0.11.2...0.11.3)
Changelog:
* disable github checks to debug the later 404 (37e8b03)
* more debugging code (5051d27)
* add some more flags to release-it command to see if i can debug this weird 404 (9f15db1)
  release-it:config { version: '0.11.3', isPreRelease: false, preReleaseId: null } +1ms
$ npm version 0.11.3 --no-git-tag-version
v0.11.3
v0.11.3
  release-it:shell {
  release-it:shell   command: 'npm version 0.11.3 --no-git-tag-version',
  release-it:shell   options: {},
  release-it:shell   code: 0,
  release-it:shell   stdout: 'v0.11.3',
  release-it:shell   stderr: ''
  release-it:shell } +365ms
  release-it:config { tagName: '0.11.3' } +364ms
  release-it:config { tagName: '0.11.3' } +0ms
$ git status --short --untracked-files=no
 M package-lock.json
 M package.json
M package-lock.json
 M package.json
  release-it:shell {
  release-it:shell   command: 'git status --short --untracked-files=no',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'M package-lock.json\n M package.json',
  release-it:shell   stderr: ''
  release-it:shell } +12ms
Changeset:
M package-lock.json
 M package.json
$ git add . --update

  release-it:shell {
  release-it:shell   command: [ 'git', 'add', '.', '--update' ],
  release-it:shell   options: {},
  release-it:shell   stdout: '',
  release-it:shell   stderr: ''
  release-it:shell } +33ms
$ git commit --message Release 0.11.3 [skip ci]
[main 508069e] Release 0.11.3 [skip ci]
 2 files changed, 2 insertions(+), 2 deletions(-)
  release-it:shell {
  release-it:shell   command: [ 'git', 'commit', '--message', 'Release 0.11.3 [skip ci]' ],
  release-it:shell   options: {},
  release-it:shell   stdout: '[main 508069e] Release 0.11.3 [skip ci]\n' +
  release-it:shell     ' 2 files changed, 2 insertions(+), 2 deletions(-)',
  release-it:shell   stderr: ''
  release-it:shell } +54ms
$ git tag --annotate --message Release 0.11.3 0.11.3

  release-it:shell {
  release-it:shell   command: [
  release-it:shell     'git',
  release-it:shell     'tag',
  release-it:shell     '--annotate',
  release-it:shell     '--message',
  release-it:shell     'Release 0.11.3',
  release-it:shell     '0.11.3'
  release-it:shell   ],
  release-it:shell   options: {},
  release-it:shell   stdout: '',
  release-it:shell   stderr: ''
  release-it:shell } +7ms
$ git symbolic-ref HEAD
refs/heads/main
refs/heads/main
  release-it:shell {
  release-it:shell   command: 'git symbolic-ref HEAD',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'refs/heads/main',
  release-it:shell   stderr: ''
  release-it:shell } +7ms
$ git for-each-ref --format="%(upstream:short)" refs/heads/main
origin/main
origin/main
  release-it:shell {
  release-it:shell   command: 'git for-each-ref --format="%(upstream:short)" refs/heads/main',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: 'origin/main',
  release-it:shell   stderr: ''
  release-it:shell } +6ms
$ git push --follow-tags

  release-it:shell {
  release-it:shell   command: [ 'git', 'push', '--follow-tags' ],
  release-it:shell   options: {},
  release-it:shell   stdout: '',
  release-it:shell   stderr: 'To github.com:metmuseum/Marble.git\n' +
  release-it:shell     '   37e8b03..508069e  main -> main\n' +
  release-it:shell     ' * [new tag]         0.11.3 -> 0.11.3'
  release-it:shell } +2s
! octokit repos.createRelease "Release 0.11.3" (0.11.3)
  release-it:github {
  release-it:github   owner: 'metmuseum',
  release-it:github   repo: 'Marble',
  release-it:github   tag_name: '0.11.3',
  release-it:github   name: 'Release 0.11.3',
  release-it:github   body: '* disable github checks to debug the later 404 (37e8b03)\n' +
  release-it:github     '* more debugging code (5051d27)\n' +
  release-it:github     '* add some more flags to release-it command to see if i can debug this weird 404 (9f15db1)',
  release-it:github   draft: false,
  release-it:github   prerelease: false
  release-it:github } +0ms
request {
  method: 'POST',
  baseUrl: 'https://api.github.com',
  headers: {
    accept: 'application/vnd.github.v3+json',
    'user-agent': 'release-it/14.5.0 octokit-rest.js/18.3.5 octokit-core.js/3.2.5 Node.js/15.12.0 (linux; x64)'
  },
  mediaType: { format: '', previews: [] },
  request: { timeout: 0, hook: [Function: bound bound register] },
  url: '/repos/{owner}/{repo}/releases',
  owner: 'metmuseum',
  repo: 'Marble',
  tag_name: '0.11.3',
  name: 'Release 0.11.3',
  body: '* disable github checks to debug the later 404 (37e8b03)\n' +
    '* more debugging code (5051d27)\n' +
    '* add some more flags to release-it command to see if i can debug this weird 404 (9f15db1)',
  draft: false,
  prerelease: false
}
POST /repos/metmuseum/Marble/releases - 404 in 77ms

  release-it:github HttpError: Not Found
  release-it:github     at /home/circleci/project/node_modules/@octokit/request/dist-node/index.js:66:23
  release-it:github     at processTicksAndRejections (node:internal/process/task_queues:94:5)
  release-it:github     at async /home/circleci/project/node_modules/release-it/lib/plugin/github/GitHub.js:215:26
  release-it:github     at async GitHub.release (/home/circleci/project/node_modules/release-it/lib/plugin/github/GitHub.js:110:7)
  release-it:github     at async runLifeCycleHook (/home/circleci/project/node_modules/release-it/lib/tasks.js:50:28)
  release-it:github     at async runTasks (/home/circleci/project/node_modules/release-it/lib/tasks.js:102:9) +84ms
  release-it:metrics {
  release-it:metrics   url: 'http://www.google-analytics.com/collect',
  release-it:metrics   statusCode: 200,
  release-it:metrics   statusMessage: 'OK',
  release-it:metrics   payload: 't=exception&exd=Error%3A+404+%28Not+Found%29'
  release-it:metrics } +4s
ERROR 404 (Not Found)
npm ERR! code 1
npm ERR! path /home/circleci/project
npm ERR! command failed
npm ERR! command sh -c release-it "patch" "--ci" "-VV" "--no-git.requireUpstream" "--set-upstream" "origin" "main"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2021-04-01T16_25_59_613Z-debug.log

Exited with code exit status 1
```

thanks again

**Comment by webpro** [comment]
Yes, maybe others can chime in. I don't have a repo handy to reproduce and see what access scope is required.

Thanks for the debug output. Now I'm also surprised it gives the 404 for you. All looks good before that.

On another note, the last part of the command does nothing: `"--set-upstream" "origin" "main"` (looks like everything works as intended anyway).
