### ISSUE TITLE
npm ERR! Version not changed

### ISSUE THREAD

**Issue by petrbela** [release-it/release-it#779]
I've just upgraded to the latest version and started getting a strange error:

```
Error: Version not changed
28 verbose stack     at module.exports (/opt/homebrew/lib/node_modules/npm/node_modules/libnpmversion/lib/version.js:46:25)
28 verbose stack     at module.exports (/opt/homebrew/lib/node_modules/npm/node_modules/libnpmversion/lib/index.js:24:10)
28 verbose stack     at async Version.change (/opt/homebrew/lib/node_modules/npm/lib/version.js:87:21)
```

It almost looks like the version is bumped first and then when `libnpmversion` checks whether it's different, it compares it to the already updated version.

Here's my release-it config:

```json
  "release-it": {
    "git": {
      "changelog": "auto-changelog --stdout --commit-limit false -u --template https://raw.githubusercontent.com/release-it/release-it/master/templates/changelog-compact.hbs",
      "commitMessage": "chore: release ${version}",
      "requireCleanWorkingDir": false,
      "tagName": "${version}"
    },
    "github": {
      "release": true
    },
    "hooks": {
      "after:bump": "auto-changelog -p"
    },
    "npm": {
      "publish": true
    },
    "plugins": {
      "@release-it/bumper": {
        "out": [
          "package.json",
          "example/package.json",
          "example/android/app/build.gradle",
          "example/ios/Podfile.lock",
          "playground/package.json",
          "playground/android/app/build.gradle",
          "playground/ios/Podfile.lock"
        ]
      },
      "@release-it/conventional-changelog": {
        "preset": "angular",
        "infile": "CHANGELOG.md"
      }
    }
  },
```

Setting `"ignoreVersion": true` didn't help.

Versions:
- release-it 14.10.0
- @release-it/bumper 2.0.0
- @release-it/conventional-changelog 3.0.1

**Comment by webpro** [comment]
Seems like the issue is that `package.json` is now bumped by both the `npm` and `@release-it/bumper` plugins, so you can remove it from the `out` array.
