### ISSUE TITLE
Publish path not being correct

### ISSUE THREAD

**Issue by ferrerojosh** [release-it/release-it#882]
I am setting `npm.publishPath` to `dist` and it works for NodeJS 14 and below. But when I use Node 16 and above, I get this error:

```
ERROR npm notice 
npm notice 📦  dist@0.1.2
npm notice === Tarball Contents ===
npm notice 13B   .npmignore
npm notice 200B  HISTORY.md
npm notice 7B    README.md
npm notice 1.4kB bin/dist.js
npm notice 1.8kB lib/dist.js
npm notice 602B  package.json
npm notice 4.5kB test/dist.test.js
npm notice 89B   test/fixtures/copyright.js
npm notice 199B  test/fixtures/input.js
npm notice 289B  test/fixtures/out/input.copyright.js
npm notice 229B  test/fixtures/out/input.copyright.min.js
npm notice 199B  test/fixtures/out/input.js
npm notice 139B  test/fixtures/out/input.min.js
npm notice 20B   test/mocha.opts
npm notice === Tarball Details ===
npm notice name:          dist
npm notice version:       0.1.2
npm notice filename:      dist-0.1.2.tgz
npm notice package size:  2.7 kB
npm notice unpacked size: 9.7 kB
npm notice shasum:        8898629cc251297e36d1354a9a9598619aba5b1a
npm notice integrity:     sha512-TmsZfJybRs3IZ[...]frqZyuqkz/sOQ==
npm notice total files:   14
npm notice
npm notice Publishing to https://registry.npmjs.org/
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/dist - You do not have permission to publish "dist". Are you logged in as the correct user?
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.
```

Any idea what causes this ? I have no idea where the `dist` tarball came from. Or is this possibly because I am using `pnpm` to install ? It shouldn't be an issue since switching (using nvm) from 16 to 14 fixes the issue outright.

**Comment by webpro** [comment]
Perhaps you need to `npm login` again when switching Node.js versions?

**Comment by ferrerojosh** [comment]
> Perhaps you need to `npm login` again when switching Node.js versions?

I already did `npm login` before running `release-it`.

**Comment by webpro** [comment]
It's weird, as the API for `npm publish` doesn't seem to have changed from v6 to v8 (at least not in this regard). You also seem to be using the same version of release-it.

Somehow the `name` of the package has changed. This might be an issue with `pnpm` versus `npm`, I can't tell. Not using `pnpm` myself, by the way. When you could verify this issue by only using `npm` and ruling out this factor we might be able to investigate further.

**Comment by ferrerojosh** [comment]
I deleted node_modules, and ran `npm install` again. Tried using `npm` purely:
```
ERROR npm ERR! code ETARGET
npm ERR! notarget No matching version found for dist@next.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
Its really strange. I switched back to node 14 and tried to publish and it works flawlessly.

**Comment by webpro** [comment]
What does a debug run give:

```
DEBUG=release-it:* release-it [...]
```

Specifically interested in the final `npm publish` command. Any difference in Node.js 14 vs 16? Could potentially be an issue with a dependency such as `execa` behaving differently.

**Comment by ferrerojosh** [comment]
npm v14:
```
  release-it:shell {
  release-it:shell   command: 'npm publish dist --tag next',
  release-it:shell   options: { write: false },
  release-it:shell   code: 1,
  release-it:shell   stdout: '',
  release-it:shell   stderr: 'npm notice \n' +
  release-it:shell     'npm notice package: nest-keycloak-connect@1.8.3-alpha.0\n' +
  release-it:shell     'npm notice === Tarball Contents === \n' +
  release-it:shell     'npm notice 1.1kB LICENSE                                                       \n' +
  release-it:shell     'npm notice 8.8kB guards/auth.guard.js                                          \n' +
  release-it:shell     'npm notice 435B  decorators/authenticated-user.decorator.js                    \n' +
  release-it:shell     'npm notice 2.3kB constants.js                                                  \n' +
  release-it:shell     'npm notice 479B  decorators/enforcer-options.decorator.js                      \n' +
  release-it:shell     'npm notice 850B  index.js                                                      \n' +
  release-it:shell     'npm notice 79B   interface/keycloak-connect-module-async-options.interface.js  \n' +
  release-it:shell     'npm notice 79B   interface/keycloak-connect-options-factory.interface.js       \n' +
  release-it:shell     'npm notice 158B  interface/keycloak-connect-options.interface.js               \n' +
  release-it:shell     'npm notice 6.0kB keycloak-connect.module.js                                    \n' +
  release-it:shell     'npm notice 4.6kB keycloak-connect.providers.js                                 \n' +
  release-it:shell     'npm notice 3.6kB services/keycloak-multitenant.service.js                      \n' +
  release-it:shell     'npm notice 1.8kB logger.js                                                     \n' +
  release-it:shell     'npm notice 1.1kB decorators/public.decorator.js                                \n' +
  release-it:shell     'npm notice 407B  decorators/resource.decorator.js                              \n' +
  release-it:shell     'npm notice 8.2kB guards/resource.guard.js                                      \n' +
  release-it:shell     'npm notice 79B   interface/role-decorator-options.interface.js                 \n' +
  release-it:shell     'npm notice 6.3kB guards/role.guard.js                                          \n' +
  release-it:shell     'npm notice 435B  decorators/roles.decorator.js                                 \n' +
  release-it:shell     'npm notice 428B  decorators/scopes.decorator.js                                \n' +
  release-it:shell     'npm notice 1.9kB util.js                                                       \n' +
  release-it:shell     'npm notice 2.0kB package.json                                                  \n' +
  release-it:shell     'npm notice 9.8kB README.md                                                     \n' +
  release-it:shell     'npm notice 1.0kB guards/auth.guard.d.ts                                        \n' +
  release-it:shell     'npm notice 170B  decorators/authenticated-user.decorator.d.ts                  \n' +
  release-it:shell     'npm notice 1.6kB constants.d.ts                                                \n' +
  release-it:shell     'npm notice 344B  decorators/enforcer-options.decorator.d.ts                    \n' +
  release-it:shell     'npm notice 44B   index.d.ts                                                    \n' +
  release-it:shell     'npm notice 565B  interface/keycloak-connect-module-async-options.interface.d.ts\n' +
  release-it:shell     'npm notice 228B  interface/keycloak-connect-options-factory.interface.d.ts     \n' +
  release-it:shell     'npm notice 3.9kB interface/keycloak-connect-options.interface.d.ts             \n' +
  release-it:shell     'npm notice 1.6kB keycloak-connect.module.d.ts                                  \n' +
  release-it:shell     'npm notice 463B  keycloak-connect.providers.d.ts                               \n' +
  release-it:shell     'npm notice 702B  services/keycloak-multitenant.service.d.ts                    \n' +
  release-it:shell     'npm notice 710B  logger.d.ts                                                   \n' +
  release-it:shell     'npm notice 825B  decorators/public.decorator.d.ts                              \n' +
  release-it:shell     'npm notice 226B  decorators/resource.decorator.d.ts                            \n' +
  release-it:shell     'npm notice 985B  guards/resource.guard.d.ts                                    \n' +
  release-it:shell     'npm notice 375B  interface/role-decorator-options.interface.d.ts               \n' +
  release-it:shell     'npm notice 881B  guards/role.guard.d.ts                                        \n' +
  release-it:shell     'npm notice 384B  decorators/roles.decorator.d.ts                               \n' +
  release-it:shell     'npm notice 261B  decorators/scopes.decorator.d.ts                              \n' +
  release-it:shell     'npm notice 618B  util.d.ts                                                     \n' +
  release-it:shell     'npm notice === Tarball Details === \n' +
  release-it:shell     'npm notice name:          nest-keycloak-connect                   \n' +
  release-it:shell     'npm notice version:       1.8.3-alpha.0                           \n' +
  release-it:shell     'npm notice package size:  16.7 kB                                 \n' +
  release-it:shell     'npm notice unpacked size: 76.7 kB                                 \n' +
  release-it:shell     'npm notice shasum:        d73add764cfae1a21e86f8cf245350a0c600ede4\n' +
  release-it:shell     'npm notice integrity:     sha512-+hVlCl9SplmXz[...]R3ma/x6kYIaOA==\n' +
  release-it:shell     'npm notice total files:   43                                      \n' +
  release-it:shell     'npm notice \n' +
  release-it:shell     'npm ERR! code E400\n' +
  release-it:shell     'npm ERR! 400 Bad Request - PUT https://registry.npmjs.org/nest-keycloak-connect - deprecations must be strings\n' +
  release-it:shell     '\n' +
  release-it:shell     'npm ERR! A complete log of this run can be found in:\n' +
  release-it:shell     'npm ERR!     C:\\Users\\~~\\AppData\\Roaming\\npm-cache\\_logs\\2022-04-12T08_06_50_771Z-debug.log\n'
  release-it:shell } +12s
```

It puts up a deprecation warning error since I unpublished that version just to test this case, we are interested in the publish path so the above shouldn't be an issue. What is wrong is below.

npm v16:
```
 release-it:shell {
  release-it:shell   command: 'npm publish dist --tag next',
  release-it:shell   options: { write: false },
  release-it:shell   code: 1,
  release-it:shell   stdout: '',
  release-it:shell   stderr: 'npm ERR! code ETARGET\n' +
  release-it:shell     'npm ERR! notarget No matching version found for dist@next.\n' +
  release-it:shell     'npm ERR! notarget In most cases you or one of your dependencies are requesting\n' +
  release-it:shell     "npm ERR! notarget a package version that doesn't exist.\n" +
  release-it:shell     '\n' +
  release-it:shell     'npm ERR! A complete log of this run can be found in:\n' +
  release-it:shell     'npm ERR!     C:\\Users\\~~\\AppData\\Local\\npm-cache\\_logs\\2022-04-12T08_09_02_418Z-debug-0.log\n'
  release-it:shell } +5s
  release-it:npm Error: npm ERR! code ETARGET
  release-it:npm npm ERR! notarget No matching version found for dist@next.
  release-it:npm npm ERR! notarget In most cases you or one of your dependencies are requesting
  release-it:npm npm ERR! notarget a package version that doesn't exist.
  release-it:npm
  release-it:npm npm ERR! A complete log of this run can be found in:
  release-it:npm npm ERR!     C:\Users\~~\AppData\Local\npm-cache\_logs\2022-04-12T08_09_02_418Z-debug-0.log
  release-it:npm
  release-it:npm     at G:\~~\nest-keycloak-connect\node_modules\release-it\lib\shell.js:62:18
  release-it:npm     at G:\~~\nest-keycloak-connect\node_modules\shelljs\src\exec.js:145:9
  release-it:npm     at ChildProcess.exithandler (node:child_process:406:5)
  release-it:npm     at ChildProcess.emit (node:events:520:28)
  release-it:npm     at maybeClose (node:internal/child_process:1092:16)
  release-it:npm     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) +0ms
  release-it:metrics RequestError: getaddrinfo ENOENT www.google-analytics.com
  release-it:metrics     at ClientRequest.<anonymous> (G:\~~\nest-keycloak-connect\node_modules\got\dist\source\core\index.js:962:111)
  release-it:metrics     at Object.onceWrapper (node:events:640:26)
  release-it:metrics     at ClientRequest.emit (node:events:532:35)
  release-it:metrics     at ClientRequest.origin.emit (G:\~~\nest-keycloak-connect\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
  release-it:metrics     at Socket.socketErrorListener (node:_http_client:442:9)
  release-it:metrics     at Socket.emit (node:events:520:28)
  release-it:metrics     at emitErrorNT (node:internal/streams/destroy:157:8)
  release-it:metrics     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
  release-it:metrics     at processTicksAndRejections (node:internal/process/task_queues:83:21)
  release-it:metrics     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) +24s
  ```

**Comment by webpro** [comment]
Not sure what release-it can do here, since with a manual publish you seem to have the same issue. That's why I'm closing this issue.

You can use `--disable-metrics` to prevent the request to `google-analytics.com` (not an issue though, it's fire-and-forget).

**Comment by Drapegnik** [comment]
@ferrerojosh, I had the same issue, and solved it with:
```
publishPath: './dist/',
```

**Comment by lallenfrancisl** [comment]
This is not related to publishPath but rather files field in package.json, atleast that's what the issue was for me. I had
```
files: ["./"]
```
Changed it to
```
files: ["./**, ./*"]
```

And it got fixed
