### ISSUE TITLE
How to upgrade configuration to avoid new v15 "Unexpected identifier" error?

### ISSUE THREAD

**Issue by hernanmd** [release-it/release-it#906]
I'm running Node.js v10.18.1, npm 6.14.17, and Release It! v15.0.0
Here's what I'm seeing:

```
❯ release-it
/Users/ppp/.nvm/versions/node/v10.18.1/lib/node_modules/release-it/bin/release-it.js:3
import updater from 'update-notifier';
       ^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

This is my .release-it:

```
{
    "git": {
        "commitMessage": "Release v${version}",
        "tagAnnotation": "Release v${version}",
        "requireCleanWorkingDir": false,
        "changelog": "npx auto-changelog --stdout --commit-limit false -u --template ./.changelog.hbs"
    },
    "github": {
        "release": true,
        "releaseName": "v${version}",
        "tokenRef": "GITHUB_TOKEN"
    },
    "npm": {
        "publish": false
      },
    "hooks": {
        "after:bump": "npx auto-changelog -p"
      }
  }
  %
```

and my packages.json
```

{
  "name": "pi",
  "version": "0.5.9",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "Hernán Morales Durand",
  "license": "MIT",
  "devDependencies": {
    "@release-it/conventional-changelog": "^1.1.0"
  },
  "dependencies": {
    "release-it": "^13.6.3"
  }
}
```

I wonder if I should add something like   "type": "module", in packages.json and enable nodeJs experimental modules somewhere? (e.g. node --experimental-modules)

**Comment by webpro** [comment]
Please see the announcement at https://github.com/release-it/release-it#announcement

You need at least Node.js v14.9 for release-it v15. Stay on release-it v14 for older versions of Node.js

By the way, this `package.json` is odd. I would recommended to have both `release-it` and plugin packages to be `devDependencies` and that their versions match what's installed by npm (`^13.6.3` should not install v15?).

**Comment by hernanmd** [comment]
Thanks @webpro, I've upgraded node using [this thread](https://stackoverflow.com/questions/11284634/upgrade-node-js-to-the-latest-version-on-mac-os) and my packages.json
